### ISSUE TITLE
examplemod included in version 4.4.9 on CurseForge

### ISSUE THREAD

**Issue by DaemonUmbra** [Hunternif/AntiqueAtlas#191] opened 2018-06-05 03:49 UTC
The 4.4.9 release here on GitHub seems to have had that derp fixed, however the CurseForge version seems to still have it

**Comment by DaemonUmbra** [comment] 2018-06-05 03:49
![image](https://user-images.githubusercontent.com/5004171/40954306-f910fca0-6851-11e8-882e-173b32a295b4.png)

**Comment by tyra314** [comment] 2019-01-12 17:55
Duplicate of #171

**Closed as completed by tyra314** 2019-01-12 17:55 UTC
Labels: type: duplicate
