### ISSUE TITLE
Markers dont work in nether

### ISSUE THREAD

**Issue by JaclynTheCat** [Hunternif/AntiqueAtlas#298] opened 2021-01-15 01:49 UTC
So I tried to create a nether portal marker where mine was so I can easily make my way back to it, but It wouldnt save the marker. Think you could fix that in a new update?

**Comment by tyra314** [comment] 2021-01-15 12:36
Which version of Minecraft, Forge/Fabric, AntiqueAtlas are you using?

**Comment by wiloxe** [comment] 2021-01-30 19:48
They don't directly show up but will later. (Haven't tested around enough)
Forge 35.1.37
antiqueatlas-5.4.4-forge

**Comment by ITCMD** [comment] 2021-02-27 14:47
Can confirm, also having this issue on forge 35.1.28 with antiqueatlas 5.4.4

**Comment by jimmytrouser** [comment] 2021-03-06 21:07
Same for fabric version 5.4.4.  Also in other dimensions like mining ones.

**Comment by tyra314** [comment] 2021-04-09 01:10
Please provide more information. I wasn't able to reproduce this issue. Are you playing on a server or single-player? How many markers do you have? 

> They don't directly show up but will later.

What exactly does "later" mean? Does it just take time, or on leave and getting back into the nether fix it? Or a relog?

**Comment by ITCMD** [comment] 2021-04-09 14:00
When placing the marker in the nether, they do not show up on my atlas or any other users atlas. This persists on opening and closing it. I believe it only showed up after a server restart, although it may have been at a different time.

I also experienced an issue in third party dimensions (namely the undergarden) where I could mark the portal, but the marker disappeared after unloading the chunks.

Seems like there are numerous bugs in other dimensions

**Comment by tyra314** [comment] 2021-04-09 16:55
So you're saying that the markers are visible at first, but disappear later. And then even later they come back? 

Also, you're talking about server restart, does that mean you are playing on a server? Have you tried if restarting the client helps?

**Comment by ITCMD** [comment] 2021-04-12 13:34
> So you're saying that the markers are visible at first, but disappear later. And then even later they come back?
> 
> Also, you're talking about server restart, does that mean you are playing on a server? Have you tried if restarting the client helps?

Sometimes they're visible at first. When I first started using it in the Nether, they did not and I figured it was disabled in the nether. Then a few days later I can back and they were there. Other times it looks like theyre working great, then they stop.

Yes I am on a server, no relogging or restarting client does not help.

**Comment by ursacascadia** [comment] 2021-04-15 02:06
This is happening for me as well.

**Comment by MilkMan1776** [comment] 2021-05-05 02:40
They can be fixed by reloading the save

**Comment by TinyBoxer86** [comment] 2021-07-30 16:35
This happens to me too, reloading doesn't seem to help any though. I just can't place markers in the nether/other dimensions at all. 
edit: forgot to mention I'm using this in a fabric pack!

**Comment by ITCMD** [comment] 2021-08-01 18:25
> This happens to me too, reloading doesn't seem to help any though. I just can't place markers in the nether/other dimensions at all.

I still have this issue now and then too without reloading helping. Tell me, do you have any of these mods too @TinyBoxer86?

```
AmbientSounds_v3.1.4_mc1.16.4.jar
chunkloaders-1.1.6-mc1.16.5.jar
create-mc1.16.5_v0.3.2b.jar
create-stuff-additions1.16.5_v1.0.6.jar
CreativeCore_v2.0.10_mc1.16.4.jar
disenchanter.jar
flywheel-1.16-0.1.1.jar
furniture-7.0.0-pre19-1.16.3.jar
goldenhopper-1.2.0-1.16.3.jar
jei-1.16.4-7.6.1.71.jar
mumblelink-1.16.4-4.6.2.jar
OptiFine_1.16.4_HD_U_G7.jar
Simple+guns+reworked+1.16.5+v1.4.jar
SoundFilters-0.14_for_1.16.2.jar
supermartijn642configlib-1.0.5-mc1.16.jar
TerraForged-1.16.4-0.2.7.jar
The_Undergarden-1.16.4-0.4.2.jar
TravelersBackpack-1.16.4-5.3.8.jar
[1.16.5]LagMeter-1.3.5.jar
```

**Comment by TinyBoxer86** [comment] 2021-08-01 23:09
> 
> 
> > This happens to me too, reloading doesn't seem to help any though. I just can't place markers in the nether/other dimensions at all.
> 
> I still have this issue now and then too without reloading helping. Tell me, do you have any of these mods too @TinyBoxer86?
> 
> ```
> AmbientSounds_v3.1.4_mc1.16.4.jar
> chunkloaders-1.1.6-mc1.16.5.jar
> create-mc1.16.5_v0.3.2b.jar
> create-stuff-additions1.16.5_v1.0.6.jar
> CreativeCore_v2.0.10_mc1.16.4.jar
> disenchanter.jar
> flywheel-1.16-0.1.1.jar
> furniture-7.0.0-pre19-1.16.3.jar
> goldenhopper-1.2.0-1.16.3.jar
> jei-1.16.4-7.6.1.71.jar
> mumblelink-1.16.4-4.6.2.jar
> OptiFine_1.16.4_HD_U_G7.jar
> Simple+guns+reworked+1.16.5+v1.4.jar
> SoundFilters-0.14_for_1.16.2.jar
> supermartijn642configlib-1.0.5-mc1.16.jar
> TerraForged-1.16.4-0.2.7.jar
> The_Undergarden-1.16.4-0.4.2.jar
> TravelersBackpack-1.16.4-5.3.8.jar
> [1.16.5]LagMeter-1.3.5.jar
> ```

You're using forge, right? I'm using it in a fabric pack, so I can't be of much help there. Should have mentioned that in my original comment, my bad!

**Comment by Lictor000** [comment] 2022-01-28 09:16
Hi,
me and my friends are having more or less the same issue on a server. (Using the Crucial 2 modpack by Vazkii; Didn't have the occasion to try it on singleplayer yet).
Whenever we try to add a marker in the nether, we have to try multiple times before it gets registered on the map.
Sometimes you need just a couple of tries, but you often need to try even 10+ times. It eventually works, but it is a bit frustrating to add markers. 
Everything works just fine in the overworld. We didn't reach The End yet, so don't know about that.

Minecraft version: 1.16.5
Mod version: antiqueatlas-6.0.1-forge-mc1.16.5
Forge version installed on the server: 36.2.22

**Comment by Lictor000** [comment] 2022-02-01 14:11
> Hi, me and my friends are having more or less the same issue on a server. (Using the Crucial 2 modpack by Vazkii; Didn't have the occasion to try it on singleplayer yet). Whenever we try to add a marker in the nether, we have to try multiple times before it gets registered on the map. Sometimes you need just a couple of tries, but you often need to try even 10+ times. It eventually works, but it is a bit frustrating to add markers. Everything works just fine in the overworld. We didn't reach The End yet, so don't know about that.
> 
> Minecraft version: 1.16.5 Mod version: antiqueatlas-6.0.1-forge-mc1.16.5 Forge version installed on the server: 36.2.22

I can add a few more info. It seems that Wiloxe was somewhat right.
Looking at the server's console I could see that the markers were being registered, despite not being shown in the Atlas.
A couple of days ago, it turned out that many places we marked suddenly were flooded with many duplicate marks (I guess our previously "failed" attempts). We deleted the duplicates, and yesterday many places we marked in the Nether were no longer displayed on the map. It seems then that the problem is a visual bug: the markers are there, but most of the time are not displayed for some reason.

**Comment by OverEarth12** [comment] 2023-01-24 03:57
I think I found cause of this: If you add marker in some dimension first, like add marker in Overworld first, will not add marker in other dimension like nether anymore. I tested by create new world and go to nether to add marker there first and come back to overworld, it can't add marker on Overworld anymore. (In log, it's said marker has created both time I add marker in nether and overworld through, but it's not showing in atlas.)

**Closed as completed** 2023-02-01 20:40 UTC
Labels: type: bug, version: 1.16, mod loader: fabric, mod loader: forge, version: 1.18
