### ISSUE TITLE
Cant load

### ISSUE THREAD

**Issue by Hecate-Sama** [Hunternif/AntiqueAtlas#339] opened 2021-04-12 18:28 UTC
**Describe the bug**
A clear and concise description of what the bug is. When I try to start Minecraft it says antique atlas cant load

**To Reproduce**
1. Go to 'Minecraft Launcher'
2. Click on 'Start'

**Expected behavior**
A clear and concise description of what you expected to happen. Well it had started fine before but I just restarted and know its broken.

**Screenshots**
If applicable, add screenshots to help explain your problem. I cant

**Forge version information (please complete the following information):**
 - Minecraft: [e.g. 1.16.4] 1.16.5
 - Forge: [e.g. 35.1.37] 36.1.0
 - AntiqueAtlas: [e.g. 5.4.2-forge] 5.4.4

**Fabric version information (please complete the following information):**
 - Minecraft: [e.g. 1.16.5]
 - Fabric Launcher: [e.g. 0.11.1]
 - Fabric API: [e.g. 0.29.4]
 - AntiqueAtlas: [e.g. 5.4.2-fabric]

**Additional context**

**Comment by tyra314** [comment] 2021-04-12 19:12
Duplicate of #314

**Closed as completed by tyra314** 2021-04-12 19:12 UTC
Labels: type: duplicate, version: 1.16, mod loader: forge
