### ISSUE TITLE
Crash probably link to mod.

### ISSUE THREAD

**Issue by Fanthoume** [Hunternif/AntiqueAtlas#349] opened 2021-05-08 17:12 UTC
**Describe the bug**
basically my game can't connect to any server or join any new or existing minecraft world when the mod is installed.
i tried to using with multiple other mods and also tried to launch the game only using this mod.
I keep getting stuck when the joining world text pop up, leaving me no choice but to click with my mouse and then the game exit leaving me with an exit code 0.
it seems related to my computer apparently

**To Reproduce**
apparently it seems impossible to reproduce the bug
it just doesn't happen when i don't have the mod in my mods folder

**Expected behavior**
when the mod is installed can't join any world.
when it's not i can.

**Screenshots**
my game crashed when i tried to join a new or existing world on the screen i can't do anything or it will crash
![image](https://user-images.githubusercontent.com/83879029/117547389-a39f2700-b02f-11eb-85e3-91be3343261b.png)

leaving an exit code : 0
![image](https://user-images.githubusercontent.com/83879029/117547374-9124ed80-b02f-11eb-9d2a-1e82d4bef353.png)

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.4
 - AntiqueAtlas: 5.4.4-forge
 - Antiquewaystones - 1.2

**Additional context**
i tried using 3 different launchers and it didn't change anything between the 3 of them.
- curseforge
-MultiMc
-gbLau

**Comment by tyra314** [comment] 2021-05-09 09:21
Duplicate of #314

**Closed as completed by tyra314** 2021-05-09 09:21 UTC
Labels: type: bug, type: duplicate, version: 1.16, mod loader: forge
