### ISSUE TITLE
Crash Antique Atlas + Byg (Biomes you'll go)

### ISSUE THREAD

**Issue by KirbyBrasse** [Hunternif/AntiqueAtlas#356] opened 2021-06-07 03:17 UTC
I was playing when i wanted to restart my save to lag less, but i just couldn't connect back, it happen i probably crossed a particular biome of the mode BYG that just can't be loaded correctly by the antiqueAtlas.
When i remove Antique Atlas my save is playable again, otherwise i cant the game crash when 100% loading of the world is done.

i'm playing on the latest forge version with the latest Antique Atlas edition

i join my crahs log
an extract: 
" [07juin2021 05:02:21.492] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Ooursonne, --version, 1.16.5-forge-36.1.23, --gameDir, C:\Users\malha\AppData\Roaming\.minecraft, --assetsDir, C:\Users\malha\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, 06dc0c56de5046b5981360fffca9d870, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.23, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[07juin2021 05:02:21.495] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation
[07juin2021 05:02:21.509] [main/WARN] [cpw.mods.modlauncher.SecureJarHandler/]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[07juin2021 05:02:21.630] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[07juin2021 05:02:21.631] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\malha\AppData\Roaming\.minecraft\mods\OptiFine_1.16.5_HD_U_G8.jar
[07juin2021 05:02:21.633] [main/INFO] [optifine.OptiFineTransformer/]: Target.PRE_CLASS is available
[07juin2021 05:02:21.722] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[07juin2021 05:02:21.752] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/malha/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[07juin2021 05:02:21.758] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[07juin2021 05:02:23.648] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[07juin2021 05:02:23.663] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[07juin2021 05:02:23.704] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 311
[07juin2021 05:02:24.207] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[07juin2021 05:02:24.313] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
[07juin2021 05:02:24.344] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5-forge-36.1.23, --gameDir, C:\Users\malha\AppData\Roaming\.minecraft, --assetsDir, C:\Users\malha\AppData\Roaming\.minecraft\assets, --uuid, 06dc0c56de5046b5981360fffca9d870, --username, Ooursonne, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release]
[07juin2021 05:02:28.339] [pool-3-thread-1/WARN] [mixin/]: Method overwrite conflict for func_185499_a in valhelsia_structures.mixins.json:BeehiveBlockMixin, previously written by com.minecraftabnormals.buzzier_bees.core.mixin.BeehiveBlockMixin. Skipping method. "

[latest.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/6605633/latest.log)

**Comment by tyra314** [comment] 2021-06-09 15:19
Duplicate of #314

**Closed as completed by tyra314** 2021-06-09 15:19 UTC
Labels: type: duplicate

**Comment by KirbyBrasse** [comment] 2021-06-10 16:34
i struggle to read and understand the solution to my problem in the link you provided and the way to procede about it
