### ISSUE TITLE
ClassNotFoundException in TextureSetConfig

### ISSUE THREAD

**Issue by sargunv** [Hunternif/AntiqueAtlas#220] opened 2019-05-19 20:14 UTC
Complete log: https://paste.ee/p/m6105

For some reason, `ResourceManager.getAllResources` is triggering the exception when loading `ResourceImpl`. Reporting here because it's being called by Antique Atlas.

The relevant exception
```
2019-05-19 13:04:40,337 ForkJoinPool.commonPool-worker-3 ERROR Could not find class in ReflectionUtil.getCallerClass(2). java.lang.ClassNotFoundException: net.minecraft.class_3306
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:141)
	at org.apache.logging.log4j.util.ReflectionUtil.getCallerClass(ReflectionUtil.java:141)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
	at net.minecraft.class_3306.<clinit>(class_3306.java:23)
	at net.minecraft.class_3294.method_14489(class_3294.java:143)
	at net.minecraft.class_3304.method_14489(class_3304.java:90)
	at hunternif.mc.atlas.client.TextureSetConfig.lambda$load$0(TextureSetConfig.java:47)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

For your convenience:
```
> !yc class_3306 1.14.1
MC 1.14.1: net/minecraft/resource/ResourceImpl
Name: xj => net/minecraft/class_3306 => net/minecraft/resource/ResourceImpl
```

**Comment by tyra314** [comment] 2019-05-20 20:52
Well, our mixins don't touch any of these classes and I cannot reproduce it with just AA, so I suspect some other mod causing this 🤷‍♂

Have you tried running the pack without AA?

**Comment by tyra314** [comment] 2019-11-09 15:24
I'm going to close this issue, because:
- I wasn't able to reproduce this
- It's for 1.14.1, which isn't supported anymore
- The crash log isn't available anymore. (Guys, just use [gist](https://gist.github.com/)s!)
- I don't think it was caused by AA in the first place

If this issue comes back with the current version, feel free to reopen this.

**Closed as completed by tyra314** 2019-11-09 15:24 UTC
Labels: type: bug, status: unconfirmed, version: 1.14, mod loader: fabric
