### ISSUE TITLE
crash on server.

### ISSUE THREAD

**Issue by Wedge1453** [Hunternif/AntiqueAtlas#363] opened 2021-06-23 14:37 UTC
so I have a modpack and someone sent me this crash log, he gets this when he plays multiplayer through hamachi, I guess it is caused by Antique Atlas: https://github.com/NinaEmerly/minecraftError/blob/main/crash-2021-06-21_18.02.54-server.txt

**Comment by tyra314** [comment] 2021-06-23 14:40
Duplicate of #314

**Closed as completed by tyra314** 2021-06-23 14:40 UTC
Labels: type: duplicate
