### ISSUE TITLE
Game crash when click or press escape

### ISSUE THREAD

**Issue by userr123456789** [Hunternif/AntiqueAtlas#426] opened 2022-05-07 19:18 UTC
**Describe the bug**
whenever i open the map using 'M' and click on anything or press 'escape' the game crashes, any other key works fine

**To Reproduce**
1. Open map with the M key
2. Left click or press escape
3. See error

**Expected behavior**
map opens and closes correctly/i can interact with it.

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.20
 - AntiqueAtlas: 5.4.4

**Additional context**

[crash-2022-05-07_13.47.16-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/8645809/crash-2022-05-07_13.47.16-client.txt)

[crash-2022-05-07_14.05.18-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/8645810/crash-2022-05-07_14.05.18-client.txt)

**Comment by tyra314** [comment] 2022-05-08 14:03
Duplicate of #425

**Closed as completed by tyra314** 2022-05-08 14:03 UTC
Labels: type: duplicate, version: 1.16, mod loader: forge
