### ISSUE TITLE
[fabric] marker sizes don't work

### ISSUE THREAD

**Issue by WHiZSTA** [Hunternif/AntiqueAtlas#353] opened 2021-05-18 00:58 UTC
changing the marker sizes doesnt affect their size on the minimap. i've tried 16, 32, and 64.

Minecraft: [1.16.5]
Fabric Launcher: [0.11.1]
Fabric API: [0.32.5]
AntiqueAtlas: [5.4.4-fabric]

**Comment by tyra314** [comment] 2021-05-19 08:25
Duplicate of #329

**Closed as completed by tyra314** 2021-05-19 08:25 UTC
Labels: type: duplicate
