### ISSUE TITLE
Grey outline on the atlas

### ISSUE THREAD

**Issue by Degostor** [Hunternif/AntiqueAtlas#399] opened 2021-10-14 02:39 UTC
**Describe the bug**
When I open the Atlas book, 

**To Reproduce**
1. Open a world
2. Put the Atlas in the hotbar
3. Select the Atlas
4. All the "unexplored" areas appear grey with some sort of yellow and pink outlines

**Expected behavior**
The "unexplored" Area should appear like the color from the "explored" area

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/80651955/137240898-1174eca2-9a84-499e-a43f-91e1d5b5872c.PNG)
![ea](https://user-images.githubusercontent.com/80651955/137240905-4dca59b0-50dd-4953-b7c8-88cec70717b2.PNG)

**Fabric version information (please complete the following information):**
 - Minecraft: [e.g. 1.17.1]
 - 1.17.1
 - Fabric Launcher: [e.g. 0.11.1]
 - 0.11.6
 - Fabric API: [e.g. 0.40.8]
 - 0.40.8
 - AntiqueAtlas: [e.g. 5.4.2-fabric]
 - 6.0.0

**Comment by tyra314** [comment] 2021-10-22 22:51
This is a duplicate of #393. Please update to the latest version

**Closed as completed by tyra314** 2021-10-22 22:51 UTC
Labels: type: duplicate
