### ISSUE TITLE
Water Bug : Forge Version 1.16.4

### ISSUE THREAD

**Issue by SheltieChan** [Hunternif/AntiqueAtlas#313] opened 2021-02-03 08:55 UTC
The atlas is seemingly under the water when held while looking at the water.

![image](https://user-images.githubusercontent.com/56488659/106722181-a3783100-65d3-11eb-9fba-446a7c57bcd1.png)

**Comment by tyra314** [comment] 2021-02-03 10:53
Duplicate of #301

**Comment by tyra314** [comment] 2021-02-03 10:53
Are you running with Optifine?

**Closed as completed by tyra314** 2021-02-03 10:53 UTC
Labels: type: duplicate, version: 1.16, mod loader: forge

**Comment by SheltieChan** [comment] 2021-02-14 00:42
Yes
