### ISSUE TITLE
Crashes on startup 1.18.2 (Forge)

### ISSUE THREAD

**Issue by LexaWB** [Hunternif/AntiqueAtlas#445] opened 2022-10-02 01:06 UTC
Minecraft crashes on startup, does not open before error occurs (exit code 1)

**Comment by tyra314** [comment] 2022-10-03 10:06
Please provide a crash log

**Comment by LexaWB** [comment] 2022-10-05 22:31
there was no crash log available to copy

**Comment by tyra314** [comment] 2022-10-07 22:58
Then add the architectury-api mod.

**Comment by tyra314** [comment] 2022-10-07 22:59
Duplicate of #444

**Closed as completed by tyra314** 2022-10-07 22:58 UTC
Labels: mod loader: forge, version: 1.18, type: crash
