### ISSUE TITLE
Crash when starting already existing map

### ISSUE THREAD

**Issue by Krampus69** [Hunternif/AntiqueAtlas#413] opened 2021-11-27 22:51 UTC
**Describe the bug**
Crash when opening an already existing mod.

**To Reproduce**
You probably won't be able to because this crash occurs on a modpack that hasn't been released yet. Although I managed to get a crashy report here : 
https://crashy.net/YDkRnNF4ng2clQcU7iOW

**Version information (please complete the following information):**
 - AntiqueAtlas: antiqueatlas-5.4.4-forge
 - Minecraft: 1.16.5
 - Forge: 36.2.9
  The crashy report already sums up anything you need to know on my specs, that tool si pretty handy maybe you'll recognize an error in the report

Also, launching again the world right after the crash (with notenoughcrashes for example) doesn't trigger another crash, the level starts. 
Thank you for your amazing work, if you get any ideas about why this is happening really anything could help right now 👍

**Comment by tyra314** [comment] 2021-12-10 22:00
Duplicate of #314

That has been fixed for a while now. Please update.

**Closed as completed by tyra314** 2021-12-10 22:00 UTC
Labels: type: duplicate
