### ISSUE TITLE
alignRight = true is not moving the map to the right.

### ISSUE THREAD

**Issue by danemorgan** [Hunternif/AntiqueAtlas#371] opened 2021-07-21 09:26 UTC
**Describe the bug**
alignRight = true is not moving the map to the right.

**To Reproduce**
1. Close game and launcher
2. Open antiqueatlas.client.toml
3. Change alignRight from false to true
4. Restart game
4. MiniMap is still in the top left positiion.

**Expected behavior**
Minimap is expected to move to the top right corner.

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.32
 - AntiqueAtlas: 5.4.4-forge

**Comment by tyra314** [comment] 2021-07-22 21:30
Duplicate of #289

**Closed as completed by tyra314** 2021-07-22 21:30 UTC
