### ISSUE TITLE
Broken hand held book display with custom resource packs.

### ISSUE THREAD

**Issue by PapiOphidian** [Hunternif/AntiqueAtlas#414] opened 2021-12-10 21:42 UTC
When the Antique Atlas is held in the hand and there is a custom resource pack in use (I'm not sure if it has to be affecting Maps or whatever. I've only tested this with Vanilla Normals Renewed by Poudingue)

**To Reproduce**
1. Download and apply a resource pack (I use Vanilla Normals Renewed. My wife said she hasn't had an issue with a resource pack adding only CEM)
2. Hold an antique atlas in your hand.
3. Observe that the antique atlas looks radically different than it does without a resource pack

**Expected behavior**
The design should stay consistent.

**Version information (please complete the following information):**
 - AntiqueAtlas: 6.0.1
 - Minecraft: 1.16.5
 - Forge: 36.2.20
 
 **Additional Context**
 This has been occurring for a while and is not a new issue. I meant to report a long time ago but forgot.

**Comment by tyra314** [comment] 2021-12-10 21:58
A screenshot would really help.

**Comment by PapiOphidian** [comment] 2021-12-13 21:11
Sorry for the long delay
![Screenshot 2021-12-13 141044](https://user-images.githubusercontent.com/25259648/145889409-7e6fce42-11f0-45da-a51a-9420a472e06f.png)
.

**Comment by tyra314** [comment] 2022-09-13 13:28
I tried it today with 6.2.0. SEUS Shaders are all kinds of fucked up for me (even without AA), but the texture of the atlas doesn't look like in your image. Neither with or without the texture pack. So, either, the issue is fixed, or I can't reproduce it, which I can't do anything in either case, as Optifine doesn't play nice. So I'm closing it.

**Closed as completed by tyra314** 2022-09-13 13:28 UTC
Labels: type: bug, status: wontfix, version: 1.16, mod loader: forge
