### ISSUE TITLE
No Minversion Error

### ISSUE THREAD

**Issue by Hexidecimark** [Hunternif/AntiqueAtlas#409] opened 2021-11-16 22:14 UTC
**Describe the bug**
Forge mixins return an error on loading server related to not having a minversion

**To Reproduce**
1. Install AA 1.16.5
2. View log

**Expected behavior**
Forge returns no errors

**Screenshots**
[16Nov2021 21:10:46.805] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property

**Version information (please complete the following information):**
 - AntiqueAtlas: 6.0.1
 - Minecraft: 1.16.5
 - Forge: 36.2.4
 - Fabric Launcher: X
 - Fabric API: X
 
**Additional context**
Running https://www.curseforge.com/minecraft/modpacks/hexworks/relations/dependencies

**Comment by tyra314** [comment] 2021-11-16 23:48
Duplicate of #318

**Closed as completed by tyra314** 2021-11-16 23:48 UTC
Labels: type: duplicate
