### ISSUE TITLE
Instant crashing on 1.17.1 forge

### ISSUE THREAD

**Issue by Kryllex** [Hunternif/AntiqueAtlas#412] opened 2021-11-25 02:28 UTC
**Describe the bug**
After pressing "play" in the launcher, mc launches white for a frame or two and then crashes to an error

**To Reproduce**
1. Create a curseforge profile, select forge (any version 37.0.110 and up ive tested but maybe all of them???)
2. Add antique atlas (which auto adds cloth config api 5.1.40
3. try to launch game
4. cry as it crashes

**Expected behavior**
the game to launch with antique atlas installed and working

**Version information (please complete the following information):**
 - AntiqueAtlas: antiqueatlas-6.1.0-forge-mc1.17.1.jar
 - Minecraft: 1.17.1
 - Forge: 37.0.117

**Comment by grekdawid26** [comment] 2021-11-25 14:28
Hello,
Just wanted to add some useful things I saw in the log:

```
...
... [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
...
... [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed antiqueatlas.mixins.json:MixinPlayerEntity -> net.minecraft.world.entity.player.Player: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on tick could not find any targets matching 'tick' in net.minecraft.world.entity.player.Player. No refMap loaded. [PREINJECT Applicator Phase -> antiqueatlas.mixins.json:MixinPlayerEntity -> Prepare Injections ->  -> handler$zzb000$tick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
...
```

**Forge version:** 1.17.1-forge-37.0.118
**Mod filename:** antiqueatlas-6.1.0-forge-mc1.17.1.jar

I did not add the whole log, because there is nothing more useful there, and I would lose a lot of time redacting my local paths, usernames, etc.

PS: Sorry, I didn't check existing issues - I think it's a duplicate: #408

**Comment by tyra314** [comment] 2021-12-10 22:02
Yeah, duplicate of #408

**Closed as completed by tyra314** 2021-12-10 22:02 UTC
Labels: type: duplicate
