### ISSUE TITLE
Crashes when loading on starting screen

### ISSUE THREAD

**Issue by LittleLightz** [Hunternif/AntiqueAtlas#360] opened 2021-06-18 06:26 UTC
[crash-2021-06-18_00.24.25-server.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/6675057/crash-2021-06-18_00.24.25-server.txt)
[latest.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/6675058/latest.log)
**Describe the bug**
whenever I press play, and it starts to load. then make a new world, I go in, see stuff load, move my mouse to look around the world.. crash boom! crash ...

**To Reproduce**
1. not sure on how to do so.... I'm still very new to modpack making

**Expected behavior**
 It crashes, not sure how to describe it

**Screenshots**
I don't have any, sorda was to fast for me to remember to do it

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge:  36.1.32
 - AntiqueAtlas:  antiqueatlas-5.4.4-forge.jar

no fabric

**Additional context**
mods with the mod
MC Forge Version 1.16.5
Mods

Mystical World
BY Noobanidus
mysticalworld-1.16.4-0.3.1.11.jar

Spice of Life: Carrot Edition
BY lordcazsius
solcarrot-1.16.3-1.9.10.jar

Structurize
BY H3lay
structurize-0.13.177-ALPHA-universal.jar

"To the Bat Poles!"
BY EnderLanky
AdPoles-1.16.4-5.0.4.0-build.0095.jar

[FORGE] Outvoted
BY HowBoutNo
outvoted-1.16.5-1.2.4.jar

Abnormals Core
BY TeamAbnormals
abnormals_core-1.16.5-3.2.0.jar

Adorn (Forge)
BY Juicebus
Adorn-1.14.1+1.16.5-forge.jar

Advanced Mining Dimension
BY henkelmax
mining_dimension-1.16.5-1.0.5.jar

Alex's Mobs
BY alex1the1666
alexsmobs-1.10.1.jar

AppleSkin
BY squeek502
AppleSkin-mc1.16.2-forge-1.0.14.jar

Aquaculture 2
BY Shadowclaimer
Aquaculture-1.16.5-2.1.19.jar

Archer's Paradox
BY TeamCoFH
archers_paradox-1.16.4-1.2.0.jar

Areas
BY Serilum
areas_1.16.5-2.2.jar

AstikorCarts [Horse Carts]
BY MennoMax
astikorcarts-1.16.5-1.1.1.jar

ATO - All the Ores
BY ATMTeam
alltheores-1.3.2-1.16.5-36.1.0.jar

Atum 2: Return to the Sands
BY Shadowclaimer
Atum-1.16.5-2.2.5.jar

AutoRegLib
BY Vazkii
AutoRegLib-1.6-49.jar

Back Tools
BY ohaiiChun
BackTools-1.16.5-10.1.0.jar

Backpacked
BY MrCrayfish
backpacked-1.10.1-1.16.3.jar

Bedspreads (Forge)
BY TheIllusiveC4
bedspreads-forge-1.16.5-5.1.0.2.jar

Better Animal Models
BY cybercat5555
betteranimals-1.16.4-5.5.0.jar

Better Animals Plus
BY cybercat5555
betteranimalsplus-1.16.5-10.2.0.jar

Better Foliage
BY octarine_noise
BetterFoliage-2.6.5-Forge-1.16.5.jar

Better Than Mending
BY legobmw99
BetterThanMending-1.6.0.jar

Better Title Screen
BY Girafi
BetterTitleScreen-1.16.4-1.10.2.jar

Better Weather - Seasons, Blizzards, and more!
BY Corgi_Taco
betterweather-1.2.9.jar

Better-Shields
BY ToMe250
BetterShieldsMC1.16.3-1.1.5.jar

BetterEnd (Forge)
BY Beethoven92
betterendforge-1.16.4-1.6.0.jar

Biomes O' Plenty
BY Forstride
BiomesOPlenty-1.16.5-13.1.0.471-universal.jar

Bountiful
BY ejektaflex
Bountiful-1.16.4-3.3.1.jar

Camera Mod
BY henkelmax
camera-1.16.5-1.0.2.jar

Charm Reforged
BY svenhjol
charm-forge-1.16.5-2.3.2.jar

Charmonium Reforged
BY svenhjol
charmonium-forge-1.16.5-2.3.2.jar

Chisels & Bits
BY AlgorithmX2
chiselsandbits-0.3.4-RELEASE.jar

Citadel
BY alex1the1666
citadel-1.7.1-1.16.5.jar

Clumps
BY Jaredlll08
Clumps-6.0.0.25.jar

CoFH Core
BY TeamCoFH
cofh_core-1.16.4-1.2.1.jar

Colds: Useful Bats (FORGE)
BY Coldspell_Games
UsefulBats(1.16.4)-1.0.3.jar

Collective
BY Serilum
collective-1.16.5-2.26.jar

Comforts (Forge)
BY TheIllusiveC4
comforts-forge-1.16.5-4.0.0.4.jar

Companion bats
BY fulmineo64
companion-bats-forge-1.16.3.jar

Craftable Horse Armour & Saddle [CHA&S]
BY EwyBoy
CraftableHorseArmour-1.16.5-1.6.jar

CraftTweaker
BY Jaredlll08
CraftTweaker-1.16.5-7.1.0.314.jar

Creeper Confetti
BY SR2610
creeperconfetti-3.7.jar

Cuneiform
BY azmalent
cuneiform-1.16.3-1.2.5.jar

Curio of Undying (Forge)
BY TheIllusiveC4
curioofundying-forge-1.16.5-5.2.0.0.jar

Curios API (Forge)
BY TheIllusiveC4
curios-forge-1.16.5-4.0.5.2.jar

Doggy Talents
BY percivalalb
DoggyTalents-1.16.5-2.0.1.8.jar

Dragon Mounts: Legacy
BY WolfSh0tz
[1.16.X-1.0.10] Dragon Mounts Legacy.jar

Dude! Where's my Horse?
BY Noobanidus
dwmh-1.16.4-0.4.0.2.jar

Dungeons Mod
BY dainxt
DungeonsMod-1.16.3-1.3.20.jar

Dynamic Surroundings
BY OreCruncher
DynamicSurroundings-1.16.4-4.0.4.2.jar

Dynamic Trees
BY ferreusveritas
DynamicTrees-1.16.5-0.10.0-Beta16.jar

Dynamic Trees - Quark
BY supermassimo0310
DynamicTreesQuark-1.16.5-2.0.4.jar

Dynamic View
BY someaddon
dynviewdist-1.9.jar

End Remastered
BY jack_bagel
EndRemastered-R36.jar

Epic Fight Mod
BY maninthe_home
EpicFightMod-1.16.5-3.2.2.jar

Explorercraft - Beta 1.16.5 version is out!
BY Zathrox999
explorercraft-5.0.4.jar

Extended Caves
BY Polyvalord
extcaves-2.4.jar

Extra Golems
BY skyjay1
extragolems-11.3.1.jar

FancyMenu [Forge]
BY Keksuccino
fancymenu_2.1.0_MC_1.16.2-1.16.5.jar

First Aid
BY ichttt
firstaid-1.9.6.jar

ForgeEndertech
BY EnderLanky
ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar

Forgiving Void
BY BlayTheNinth
ForgivingVoid_1.16.5-5.2.1.jar

Friendly Fire
BY DarkhaxDev
FriendlyFire-1.16.5-7.0.2.jar

FTB Backups (Forge)
BY FTB
ftb-backups-2.1.1.6.jar

GeckoLib
BY ThanosGecko
geckolib-forge-1.16.5-3.0.41.jar

Genetic Animals
BY mokiyoki
GeneticAnimals-0_6_29.jar

GraveStone Mod
BY henkelmax
gravestone-1.16.5-1.0.4.jar

Greek Fantasy
BY skyjay1
greekfantasy-16.4.17.jar

Guard Villagers
BY almightytallestred
guardvillagers-1.16.5.1.2.4.jar

GuardsCraft
BY sgtmattbaker
guardscraft-1.16.5-1.0.0.jar

Hats
BY ohaiiChun
Hats-1.16.5-10.3.1.jar

Healing Campfire
BY Serilum
healingcampfire_1.16.5-3.2.jar

Horse Tack
BY misteriawolfe
horse_tack-3.0-1.16.3release.jar

Hunter illager
BY bagu_chan500
HunterIllager-1.16.5-1.1.2.jar

Ice and Fire: Dragons
BY alex1the1666
iceandfire-2.1.7-1.16.5.jar

iChunUtil
BY ohaiiChun
iChunUtil-1.16.5-10.4.1.jar

Ignition: EnderBags
BY Shadows_of_Fire
EnderBags-1.16.4-6.3.1.jar

Inspirations
BY KnightMiner
Inspirations-1.16.5-1.2.3.37.jar

Inventory HUD+
BY dmitrylovin
InventoryHud_[1.16.2-1.16.5].forge-3.3.0.jar

Inventory Pets
BY Purplicious_Cow_
inventorypets-1.16.5-2.0.15.jar

Iron Age Furniture
BY SkyBlade1978
ironagefurniture 1.16.4-1.16.5 0.2.0.5.jar

Iron Chests
BY ProgWML6
ironchest-1.16.4-11.2.10.jar

It's the little things
BY Zlepper
itlt-1.16.x-2.0.0.jar

Jade 🔍
BY Snownee_
Jade-1.16.4-2.7.1.jar

JEI Integration
BY SnowShock35
jeiintegration_1.16.5-7.0.1.15.jar

JEITweaker
BY Jaredlll08
JEITweaker-1.16.5-1.0.1.31.jar

JourneyMap
BY techbrew
journeymap-1.16.5-5.7.1.jar

Just Enough Items (JEI)
BY mezz
jei-1.16.5-7.7.0.106.jar

Konkrete [Forge]
BY Keksuccino
konkrete_1.1.6_MC_1.16.2-1.16.5.jar

Kotlin for Forge
BY thedarkcolour
kotlinforforge-1.12.2-obf.jar

Lootr
BY Noobanidus
lootr-1.16.4-0.0.5.17.jar

Mantle
BY mDiyo
Mantle-1.16.5-1.6.109.jar

Menu Companions
BY Fuzs_
MenuCompanions-v1.2.3-1.16.5.jar

Mermaid Tail Mod
BY ThatPreston
mermaidtail-1.4b.jar

MineColonies
BY H3lay
minecolonies-0.14.223-ALPHA-universal.jar

Mini Creepers Pets
BY kleiders3010
Creepets 1.16.5.jar

Mod Name Tooltip
BY mezz
modnametooltip_1.16.2-1.15.0.jar

Morpheus
BY Quetzi
Morpheus-1.16.5-4.2.70.jar

Mouse Tweaks
BY YaLTeR
MouseTweaks-2.14-mc1.16.2.jar

Mowzie's Mobs
BY bobmowzie
mowziesmobs-1.5.18.jar

Mutant Beasts
BY Chumbanotz
MutantBeasts-1.16.4-1.1.3.jar

Nether Portal Spread
BY Serilum
netherportalspread_1.16.5-5.1.jar

Nether's Exoticism
BY Furti_Two
nether-s-exoticism-1.16.5-1.0.5.jar

Obfuscate
BY MrCrayfish
obfuscate-0.6.2-1.16.3.jar

Oh The Biomes You'll Go
BY AOCAWOL
byg-1.2.9.jar

Organics
BY Furti_Two
Organics-1.16.5-0.1.7.jar

Pane In The Glass
BY MongoTheElder
pitg-1.16.3-1.4.2.jar

Paragliders
BY Tictim
Paraglider-1.16.5-1.3.1.1.jar

Patchouli
BY Vazkii
Patchouli-1.16.4-51.jar

Petrock - Forge
BY manmaed
petrock-0.7.8.jar

Placebo
BY Shadows_of_Fire
Placebo-1.16.4-4.5.0.jar

Platforms
BY ShetiPhian
platforms-1.16-1.7.11.jar

Project MMO
BY Harmonised_
Project_MMO-1.16.5-3.58.4.jar

Quark
BY Vazkii
Quark-r2.4-312.jar

Random Village Names
BY Serilum
randomvillagenames_1.16.5-1.1.jar

Rare Ice (Forge/Fabric)
BY shedaniel
rare-ice-0.2.2.jar

Rats
BY alex1the1666
rats-7.2.0-1.16.5.jar

Realistic Horse Genetics
BY sekelsta
horse_colors-1.16.5-1.6.0.2.jar

Realistic Torches
BY Chaosyr
RealisticTorches-1.16.5-3.1.2.jar

Save Your Pets
BY MacTso
SaveYourPets-1.16.2-1.0.0.5.jar

Security Craft
BY Geforce132
[1.16.5] SecurityCraft v1.8.22.jar

ShetiPhianCore
BY ShetiPhian
shetiphiancore-1.16-3.8.5.jar

Smaller Nether Portals
BY Serilum
smallernetherportals_1.16.5-1.6.jar

Space-Bosstools
BY mrscauthd
Space-Bosstools-1.16.5-5.3.jar

Spiders 2.0
BY TheCyberBrick
spiders-2.0-1.16.4-1.0.4.jar

Straw Golem Reborn - Forge
BY CommodoreThrawn
strawgolem-1.16-1.9.jar

Structure Gel API
BY ModdingLegacy
structure_gel-1.16.5-1.7.7.jar

Subterranean Wilderness
BY Melonslise
subwild-1.2.1.jar

Supplementaries
BY MehVahdJukaar
supplementaries-1.16.5-0.13.2.jar

SwingThroughGrass
BY exidex
swingthroughgrass-1.16.4-1.5.3.jar

Terra Incognita: The Unknown Land
BY azmalent
terraincognita-1.16.3-1.6.4.2.jar

The Abyss: Chapter II
BY y4z0n
TheAbyss2 1.9.7 1.16.5.jar

The Conjurer
BY ModdingLegacy
the-conjurer-1.16.4-1.0.13.jar

The Endergetic Expansion
BY TeamAbnormals
endergetic-1.16.4-3.0.0.jar

The King of the Villagers
BY ElvishNight
kingvillager-1.6.2.jar

The Lost Cities
BY McJty
lostcities-1.16-4.0.9-beta.jar

The Mighty Architect
BY simibubi
mightyarchitect-mc1.16.3_v0.5.jar

The Outer End
BY BlueDuckYT
OuterEnd-0.2.13.jar

The Undergarden
BY Quek04
The_Undergarden-1.16.5-0.5.3.jar

Tinkers Construct
BY mDiyo
TConstruct-1.16.5-3.0.4.197.jar

Towers Of The Wild
BY idrae_
towers_of_the_wild-1.16.4-2.0.1.jar

Traveler's Backpack
BY Tiviacz1337
TravelersBackpack-1.16.5-5.4.2.jar

Tumbleweed
BY konwboj
tumbleweed-1.16-0.4.9.jar

Two Players One Horse
BY Beethoven92
twoplayersonehorse-1.16.4-2.0.2.jar

U Team Core
BY HyCraftHD
u_team_core-1.16.5-3.2.1.196.jar

Useful Railroads
BY HyCraftHD
useful_railroads-1.16.5-1.4.6.38.jar

Useless Sword
BY Furti_Two
UselessSword-1.16.5-V1.3.3.jar

Valhelsia Core
BY ValhelsiaTeam
valhelsia_core-16.0.9.jar

Valhelsia Structures
BY ValhelsiaTeam
valhelsia_structures-1.16.5-0.1.2.jar

Villager Names
BY Serilum
villagernames_1.16.5-2.9.jar

Villagers And Monsters Mod Legacy
BY abukkezsaruj
VillagersAndMonstersLegacy2.3.jar

Waddles
BY Girafi
Waddles-1.16.5-0.8.13.jar

Wall-Jump! [FORGE]
BY genandnic
walljump-forge-1.16.4-1.3.7.jar

Water Strainer
BY Ruuubi
WaterStrainer-1.16.3-10.0.0.jar

Waystones
BY BlayTheNinth
Waystones_1.16.5-7.6.2.jar

YUNG's API (Forge)
BY YUNGNICKYOUNG
YungsApi-1.16.4-Forge-6.jar

YUNG's Better Caves (Forge)
BY YUNGNICKYOUNG
BetterCaves-Forge-1.16.4-1.1.2.jar

YUNG's Better Mineshafts (Forge)
BY YUNGNICKYOUNG
BetterMineshafts-Forge-1.16.4-2.0.4.jar

**Comment by tyra314** [comment] 2021-06-20 16:02
duplicate of #314

**Closed as completed by tyra314** 2021-06-20 16:02 UTC
