### ISSUE TITLE
When is antique atlas for mc 1.18+ coming?

### ISSUE THREAD

**Issue by Tim202110** [Hunternif/AntiqueAtlas#422] opened 2022-04-02 14:15 UTC
Its more a question than a issue

Is there any trouble in the code that is making it hard?
Did something happen to personal life that you had to put it aside.
I have been waiting for quite a while all I want is a lil bit of info then I will have more insight on how long id have to possibly wait.
This is my favorite mod to use in every version of mc but I prefer modding newer released versions of mc.

Hope you understand and give me/us a lil bit of information on how long it might take.
Maybe adding an roadmap on how far you all are gives the information I/we kinda need.

**Comment by tyra314** [comment] 2022-04-10 10:30
The worldgen change introduced in 1.18 is a bigger wall, than I thought it would be. Basically, the biome identifiers aren't a reliable source of information how the terrain looks like anymore. A while back, I posted [this screenshot](https://media.discordapp.net/attachments/286475944116355083/920459157172256788/unknown.png?width=2620&height=1314) on discord. The cliffs you can see, those are "plains" according to Minecraft. 

Combine this with the fact, that in AA, only the server scans the terrain and sends biome identifiers to the client. The problem is, biome identifiers aren't enough information for the client to select the correct texture, but the client doesn't have any other information as well. While that isn't an unsolvable problem, I haven't had the time and mental energy to tackle it.

The current state is: There is a dev build for fabric available here on Github, which should load fine, but the map has errors (like showing the cliffs from the screenshot as plains) and missing textures for the new biomes. It's also likely that the storage format for maps has to change.

**Comment by Tim202110** [comment] 2022-04-10 10:56
Ah thanks for telling. I thought the problem was probably with world gen but wanted to be sure. Again thanks.
Take your time and do what you can. Ill be patiently waiting for my favorite mod. Thanks again for your reply.

**Comment by Dr-WeiAL** [comment] 2022-05-01 17:42
It doesn't seem to work in 1.18.2

**Comment by sisby-folk** [comment] 2022-07-22 07:37
Just gonna bump here that the artifacts being referenced above have expired. Here's a build from the 1.18 branch [removed] - Noting again that this doesn't work on 1.18.2

Honestly map accuracy isn't one of those things that's super huge to us compared to having a waypoint system, a free map (using the "no item required" configuration), and limited map visibility compared to 1:1 maps. So we'd personally appreciate the 1.18.2 compatibility being patched up if at all possible 👍

**Comment by sisby-folk** [comment] 2022-07-31 06:48
We became competent at mixin and updated the mod (FOR 1.18.2 - not fixing 1.18 overall issues) in #432 - Here's a build for anyone who likes bleeding edge mods and wants to save five minutes: [antiqueatlas-6.2.0-fabric-mc1.18.2.jar.zip](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/9274437/antiqueatlas-6.2.0-fabric-mc1.18.2.jar.zip)

Do not request official support for this build.

**Comment by sisby-folk** [comment] 2022-08-09 07:00
The 1.18.2 PR has been merged and heightmap-based tiles is also in. I've had a look and think it looks great, though we'd also understand wanting to tweak it more. The main thing that's visibly missing from the 1.18 is some tile textures/mappings.

I'm not sure if the 1.18 version is also supposed to have stuff like the map keybind or minimap HUD, or whether that waws removed in an earlier version, but they're not present in builds from 1.18-fabric rn as far as we know.

**Comment by tyra314** [comment] 2022-09-11 20:36
The 7.0.0 update should pop up on CF at any moment.

**Closed as completed by tyra314** 2022-09-11 20:36 UTC
Labels: type: question
