### ISSUE TITLE
Using "m" crashes the game

### ISSUE THREAD

**Issue by SylisMC** [Hunternif/AntiqueAtlas#286] opened 2021-01-08 02:07 UTC
**Description**
As suggested by @tyra314 in [issue #282](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/282) 
IF the following config line is set to `"itemNeeded": false,` Hitting `M` renders a blank map proceeds to crash the game.

**Version** (1.16.4)
jumploader-2.1.2
antiqueatlas-5.4.0-fabric
fabric-api-0.28.4+1.16

**Logs**
[Atlast Crash.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/5784835/Atlast.Crash.txt)

**Comment by tyra314** [comment] 2021-01-09 17:44
I can't reproduce this right now, maybe it will be fixed in the upcoming version. Please report back, if it still persists.

**Comment by SylisMC** [comment] 2021-01-10 01:42
dont have the issue anymore. latest version fixed it

**Closed as completed** 2021-01-16 13:49 UTC
Labels: type: bug, version: 1.16, mod loader: fabric
