### ISSUE TITLE
Atlas Crafting Bug

### ISSUE THREAD

**Issue by Kai-Alpha12** [Hunternif/AntiqueAtlas#386] opened 2021-08-11 22:52 UTC
For some reason, people in my RL Craft server people aren't able to craft an antiqueatlas. I've tried removing the mod server side and reinstalling but people are still unable to craft it... Any ideas on what to do?

 - Forge 14.23.5.2838
 - AntiqueAtlas 1.12.2 - 4.6.3

**Comment by tyra314** [comment] 2021-08-12 21:48
I have no idea, what you're trying to say.

**Comment by Kai-Alpha12** [comment] 2021-08-12 22:44
> I have no idea, what you're trying to say.

updated to make more sense

**Comment by AiLovesAi** [comment] 2021-08-17 23:35
I am pretty sure RLCraft has mods in it removing crafting recipes. The recipe works fine and is not an Antique Atlas issue. I would check your "*scripts/*" folder in your RLCraft directory and look at the CraftTweaker scripts. They probably remove it in one of those files. They also may have a custom mod removing the recipes. Posting a log of the server could help figure out what's going on and if there are any issues registering the crafting recipe, or if, more likely, they are being removed.

**Comment by tyra314** [comment] 2022-09-11 21:05
I think I'm going to close this. 
a) There won't be an update for 1.12
b) seems working as intended in the modpack

**Closed as completed by tyra314** 2022-09-11 21:05 UTC
Labels: version: 1.12
