### ISSUE TITLE
Conflict with JustEnoughIDs

### ISSUE THREAD

**Issue by corgiblu** [Hunternif/AntiqueAtlas#201] opened 2018-08-02 03:15 UTC
JEID messes with biome ids and makes it so the atlas has all desert except for water. even configuring with the nei biome dump didn't fix the issue.

with jeid and atlas
![2018-08-01_23 10 04](https://user-images.githubusercontent.com/32643374/43560412-44b9420a-95e0-11e8-9659-945b0460c2d2.png)
without jeid
![2018-08-01_23 10 12](https://user-images.githubusercontent.com/32643374/43560403-37991974-95e0-11e8-8237-c44401a416bd.png)

not sure you'll be able to get it fixed but figured I'd let you know

**Comment by corgiblu** [comment] 2018-08-02 03:16
DimensionalDevelopment/JustEnoughIDs#27

**Comment by Hunternif** [comment] 2018-08-02 14:00
Thanks for the info!
By the way, on your screenshots the map appears at an odd zoom level, with visible artifacts. Was it always this way? Did you adjust zoom level in the settings?

**Comment by corgiblu** [comment] 2018-08-02 14:38
It's probably because I wasn't in full screen. I had 2 instances open side
by side.

**Comment by ofseaandstars** [comment] 2018-08-17 11:06
I am also experiencing this issue.

Antique Atlas: v4.4.9
JEID: v1.0.1-16

**Comment by crazyirishwrencher** [comment] 2018-08-25 05:28
Same issue.

**Comment by PulseBeat02** [comment] 2018-08-27 12:35
Duplicate of

https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/198

**Comment by corgiblu** [comment] 2018-08-27 12:59
Not a duplicate. I didn't crash. Did you even read the issue?

**Comment by PulseBeat02** [comment] 2018-08-29 18:24
Oops, wrong issue.

**Closed as completed** 2019-01-13 12:57 UTC
