### ISSUE TITLE
Can't join LAN game, "Internal Server Error".

### ISSUE THREAD

**Issue by Gazer10** [Hunternif/AntiqueAtlas#394] opened 2021-09-13 15:04 UTC
**Describe the bug**
I get the "Internal Server Error" error every time I try to join a LAN game even though both players have the mod installed. Works perfectly fine in single player though.

**To Reproduce**
1. Go to multiplayer
2. Click on join game
3. See error

**Expected behavior**
To join the multiplayer world

**Screenshots**
N/A

**Forge version information:**
 - Minecraft: 1.16.5
 - Forge: 36.1.31
 - AntiqueAtlas: 5.4.4-forge

**Additional context**
I do have a descent amount of other mods too (both players), but I don't think they're the cause (interfering with AA) since I've always had the same problem with antique atlas on my other "modpacks". **Also there isn't any crash log, simply disconnect**

Thanks

**Comment by tyra314** [comment] 2021-09-13 23:17
Duplicate of #314 

Also this bug is fixed, please update the mod.

**Closed as completed by tyra314** 2021-09-13 23:17 UTC
Labels: type: duplicate, version: 1.16, mod loader: forge
