### ISSUE TITLE
 Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by NunKi-QAQ** [Hunternif/AntiqueAtlas#462] opened 2023-03-27 08:31 UTC
**Describe the bug**
Can not login to the server after exit. An empty antique atlas is generated by right-click before the logout. 

**To Reproduce**
1. Connect to the server
2. Create an antique atlas by right-click an empty antique atlas
3. log out
4.login again 

**Expected behavior**
Be able to login to the server 

**Screenshots**
Error Message from Client:
![image](https://user-images.githubusercontent.com/62667863/227886268-86581081-10fe-486e-bc87-c3f588ae12be.png)
A list of mods I have in the server: 
![image](https://user-images.githubusercontent.com/62667863/228002870-6c6fe10e-59e6-4614-9791-03397f1f15d7.png)

**Version information (please complete the following information):**
 - AntiqueAtlas: 7.1.0
 - Minecraft: 1.18.2
 - Forge: 40.2.0
 
**Additional context**
Error Log:

[Server thread/WARN] [net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /128.146.189.81:26811
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.2.1.jar%2317!/:1.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at hunternif.mc.impl.atlas.core.WorldData.lambda$syncToPlayer$0(WorldData.java:215) ~[antiqueatlas-7.1.0-forge-mc1.18.2.jar%2339!/:?]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at hunternif.mc.impl.atlas.core.WorldData.syncToPlayer(WorldData.java:214) ~[antiqueatlas-7.1.0-forge-mc1.18.2.jar%2339!/:?]
	at hunternif.mc.impl.atlas.core.AtlasData.syncToPlayer(AtlasData.java:167) ~[antiqueatlas-7.1.0-forge-mc1.18.2.jar%2339!/:?]
	at hunternif.mc.impl.atlas.item.AtlasItem.m_6883_(AtlasItem.java:85) ~[antiqueatlas-7.1.0-forge-mc1.18.2.jar%2339!/:?]
	at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:494) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.world.entity.player.Inventory.m_36068_(Inventory.java:229) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:490) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?]
	... 9 more

**Comment by tyra314** [comment] 2023-03-30 18:47
duplicate of #461

**Closed as completed by tyra314** 2023-03-30 18:47 UTC
Labels: type: duplicate, mod loader: fabric, mod loader: forge, version: 1.18, type: crash
