### ISSUE TITLE
Vivecraft Atlas Incompatability and Crash

### ISSUE THREAD

**Issue by CPSRYAN** [Hunternif/AntiqueAtlas#421] opened 2022-02-10 20:46 UTC
I have had the same crash as #392 and can confirm the reason, when holding the atlas in your hand and with an empty offhand the game crashes. This is due to the atlas "grabbing" the players hands to hold the atlas, causing an error/conflict with vivecraft. When held in the offhand, or in the main hand with an item in the offhand, then it will simply show as normal, albeit with a duplicated arm (Also due to a conflict with vivecraft) Crash report will be submitted below. I have about 5 of the same crash report before I figured it out, holding a torch in my offhand for light (Optifine) had been saving me

Minecraft Version 1.16.5
Forge 36.2.20
AntiqueAtlas: antiqueatlas-6.0.1-forge-mc1.16.5.jar

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 10/02/22 20:38
Description: Unexpected error

java.lang.ClassCastException: org.vivecraft.render.VRPlayerRenderer cannot be cast to net.minecraft.client.renderer.entity.PlayerRenderer
	at net.minecraft.client.renderer.FirstPersonRenderer.func_228403_a_(FirstPersonRenderer.java:141) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:mixin:APP:antiqueatlas.mixins.json:HeldItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.FirstPersonRenderer.renderAtlasInBothHands(FirstPersonRenderer.java:1101) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:mixin:APP:antiqueatlas.mixins.json:HeldItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.FirstPersonRenderer.handler$zee000$renderAtlas(FirstPersonRenderer.java:1078) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:mixin:APP:antiqueatlas.mixins.json:HeldItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.FirstPersonRenderer.func_228405_a_(FirstPersonRenderer.java:469) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:mixin:APP:antiqueatlas.mixins.json:HeldItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.renderVRHand_Main(GameRenderer.java:3178) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.renderVRHands(GameRenderer.java:3114) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.renderVrFast(GameRenderer.java:3601) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:2000) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:cavesandcliffs.mixins.json:client.WorldRendererMixin,pl:mixin:APP:flywheel.mixins.json:BeginFrameMixin,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1024) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:789) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.renderSingleView(Minecraft.java:4152) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:1546) [?:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [?:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A}
	at net.minecraft.client.main.Main.main(Main.java:234) [?:?] {re:classloading,xf:Vivecraft:default}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.20.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/713464342.call(Unknown Source) [forge-1.16.5-36.2.20.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.FirstPersonRenderer.func_228403_a_(FirstPersonRenderer.java:141) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:mixin:APP:antiqueatlas.mixins.json:HeldItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.FirstPersonRenderer.renderAtlasInBothHands(FirstPersonRenderer.java:1101) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:mixin:APP:antiqueatlas.mixins.json:HeldItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.FirstPersonRenderer.handler$zee000$renderAtlas(FirstPersonRenderer.java:1078) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:mixin:APP:antiqueatlas.mixins.json:HeldItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.FirstPersonRenderer.func_228405_a_(FirstPersonRenderer.java:469) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:mixin:APP:antiqueatlas.mixins.json:HeldItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.renderVRHand_Main(GameRenderer.java:3178) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.renderVRHands(GameRenderer.java:3114) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.renderVrFast(GameRenderer.java:3601) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:2000) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:cavesandcliffs.mixins.json:client.WorldRendererMixin,pl:mixin:APP:flywheel.mixins.json:BeginFrameMixin,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1024) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:789) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['Smatiey'/145353, l='ClientLevel', x=-261.93, y=72.54, z=228.59], RemoteClientPlayerEntity['Cyanid3Apple'/140455, l='ClientLevel', x=-267.71, y=74.00, z=229.55]]
	Chunk stats: Client Chunk Cache: 1225, 841
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,81,224), Chunk: (at 0,5,0 in -16,14; contains blocks -256,0,224 to -241,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2082665 game time, 2305930 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:3272) [?:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:895) [?:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A}
	at net.minecraft.client.main.Main.main(Main.java:234) [?:?] {re:classloading,xf:Vivecraft:default}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.20.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/713464342.call(Unknown Source) [forge-1.16.5-36.2.20.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7629141968 bytes (7275 MB) / 8553758720 bytes (8157 MB) up to 12795772928 bytes (12203 MB)
	CPUs: 24
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -Xms8G -XX:+UseParallelGC -XX:ParallelGCThreads=4 -XX:MaxGCPauseMillis=3 -Xmn256M -XX:+UnlockExperimentalVMOptions
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-1.16.5_HD_U_G8_LIB.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE 
		/minecrift-1.16.5-jrbudda-7-8b.jar Vivecraft TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.20
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.20-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		NetherPortalFix_1.16.3-7.2.1.jar                  |NetherPortalFix               |netherportalfix               |7.2.1               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.145.jar                          |Just Enough Items             |jei                           |7.7.1.145           |DONE      |Manifest: NOSIGNATURE
		Ding-1.16.5-1.3.0.jar                             |Ding                          |ding                          |1.3.0               |DONE      |Manifest: NOSIGNATURE
		AttributeFix-1.16.5-10.1.3.jar                    |AttributeFix                  |attributefix                  |10.1.3              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		cavesandcliffs-1.16.5-7.2.0.jar                   |Caves and Cliffs Backport     |cavesandcliffs                |1.16.5-7.2.0        |DONE      |Manifest: NOSIGNATURE
		reap-1.16.5-1.0.0.jar                             |Reap Mod                      |reap                          |1.16.5-1.0.0        |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |DONE      |Manifest: NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |DONE      |Manifest: NOSIGNATURE
		ftb-backups-2.1.2.2.jar                           |FTB Backups                   |ftbbackups                    |2.1.2.2             |DONE      |Manifest: NOSIGNATURE
		FastSuite-1.16.4-1.1.1.jar                        |FastSuite                     |fastsuite                     |1.1.1               |DONE      |Manifest: NOSIGNATURE
		Clumps-6.0.0.27.jar                               |Clumps                        |clumps                        |6.0.0.27            |DONE      |Manifest: NOSIGNATURE
		FastWorkbench-1.16.5-4.6.1.jar                    |Fast Workbench                |fastbench                     |4.6.1               |DONE      |Manifest: NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |DONE      |Manifest: NOSIGNATURE
		Controlling-7.0.0.28.jar                          |Controlling                   |controlling                   |7.0.0.28            |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.39.jar                   |Polymorph                     |polymorph                     |1.16.5-0.39         |DONE      |Manifest: NOSIGNATURE
		Placebo-1.16.5-4.6.1.jar                          |Placebo                       |placebo                       |4.6.1               |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.5.1.jar                   |Storage Drawers               |storagedrawers                |8.5.1               |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |DONE      |Manifest: NOSIGNATURE
		configured-1.5.1-1.16.5.jar                       |Configured                    |configured                    |1.5.1               |DONE      |Manifest: NOSIGNATURE
		VivecraftForgeExtensions-1.16.4-1.3.3.jar         |Vivecraft Forge Extensions    |vivecraftforgeextensions      |1.3.3               |DONE      |Manifest: NOSIGNATURE
		Chunk Pregenerator-V1.16-3.2.1.jar                |Chunk Pregenerator            |chunkpregen                   |V1.16-3.2.1         |DONE      |Manifest: NOSIGNATURE
		antiquewaystones-1.3.jar                          |Antique Waystones             |antiquewaystones              |1.3                 |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.31.jar                |Bookshelf                     |bookshelf                     |10.4.31             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		cavebiomeapi-1.16.5-1.4.2.jar                     |CaveBiomeAPI                  |cavebiomeapi                  |1.16.5-1.4.2        |DONE      |Manifest: NOSIGNATURE
		FastFurnace-1.16.5-4.5.0.jar                      |FastFurnace                   |fastfurnace                   |4.5.0               |DONE      |Manifest: NOSIGNATURE
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |DONE      |Manifest: NOSIGNATURE
		lootr-1.16.5-0.1.11.36.jar                        |Lootr                         |lootr                         |0.1.11.35-experiment|DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.16.5-0.4.0.jar                  |AI-Improvements               |aiimprovements                |0.4.0               |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		WAWLA-1.16.5-8.0.1.jar                            |WAWLA                         |wawla                         |8.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		cloth-config-4.14.54-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.14.54             |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.133.jar         |Just Enough Resources         |jeresources                   |0.12.1.133          |DONE      |Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.3.0-11.jar            |Immersive Petroleum           |immersivepetroleum            |3.3.0-11            |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.7-143.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.7-143    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		FastLeafDecay-v25.2.jar                           |FastLeafDecay                 |fastleafdecay                 |v25.2               |DONE      |Manifest: NOSIGNATURE
		WailaHarvestability-mc1.16.x-forge-1.1.15.jar     |Waila Harvestability          |wailaharvestability           |1.1.15              |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |DONE      |Manifest: NOSIGNATURE
		corpse-1.16.5-1.0.6.jar                           |Corpse                        |corpse                        |1.16.5-1.0.6        |DONE      |Manifest: NOSIGNATURE
		antiqueatlas-6.0.1-forge-mc1.16.5.jar             |Antique Atlas                 |antiqueatlas                  |6.0.1-forge-mc1.16.5|DONE      |Manifest: NOSIGNATURE
		BetterAdvancements-1.16.5-0.1.1.115.jar           |Better Advancements           |betteradvancements            |0.1.1.115           |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: c7586fca-8c1c-48a8-8ece-f81bb975b177
	Launched Version: vivecraft-1.16.5-jrbudda-7-8b-forge
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.23, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'vivecraft'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor 
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 21
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 511.23
	OpenGlRenderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 24

**Comment by tyra314** [comment] 2022-08-01 19:04
Duplicate of #392

**Closed as completed by tyra314** 2022-08-01 19:04 UTC
Labels: type: duplicate, version: 1.16, mod loader: forge
