### ISSUE TITLE
[fabric] custom biome tilesets don't work

### ISSUE THREAD

**Issue by WHiZSTA** [Hunternif/AntiqueAtlas#354] opened 2021-05-20 10:54 UTC
i'm working on adding new definitions via the biome_textures.json and texture_sets.json in the 'config/antiqueatlas' directory, but the mod isnt using them, instead it's still making the map tile decisions via other methods. also the mod didnt make that directory, i had to, so im not even sure thats the right location for me to place those files per the instructions.

Minecraft: [1.16.5]
Fabric Launcher: [0.11.1]
Fabric API: [0.32.5]
AntiqueAtlas: [5.4.4-fabric]

**Comment by tyra314** [comment] 2021-05-20 13:07
Duplicate of #343

**Closed as completed by tyra314** 2021-05-20 13:07 UTC
Labels: type: duplicate
