### ISSUE TITLE
Crash when open atlas map near end city.

### ISSUE THREAD

**Issue by XiaoYueZero** [Hunternif/AntiqueAtlas#217] opened 2019-05-01 11:08 UTC
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2019-05-01 18:51:09 CST
Description: Rendering screen

java.lang.NullPointerException
    at hunternif.mc.atlas.registry.MarkerType.calculateMip(MarkerType.java:139)
    at hunternif.mc.atlas.client.gui.GuiAtlas.renderMarker(GuiAtlas.java:888)
    at hunternif.mc.atlas.client.gui.GuiAtlas.drawScreen(GuiAtlas.java:739)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
  Screen name: hunternif.mc.atlas.client.gui.GuiAtlas
  Mouse location: Scaled: (213, 119). Absolute: (427, 240)
  Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Z'/83, l='MpServer', x=-215.03, y=83.59, z=-1494.85]]
  Chunk stats: MultiplayerChunkCache: 592, 592
  Level seed: 0
  Level generator: ID 09 - lostcities_bop, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (172,64,265), Chunk: (at 12,4,9 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 103186 game time, 42008 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 44 total; [EntityEnderman['末影人'/128, l='MpServer', x=-260.50, y=57.00, z=-1463.50], EntityEnderman['末影人'/130, l='MpServer', x=-272.12, y=56.00, z=-1417.54], EntityEnderman['末影人'/131, l='MpServer', x=-259.27, y=60.00, z=-1417.33], EntityEnderman['末影人'/132, l='MpServer', x=-261.50, y=60.00, z=-1416.50], EntityEnderman['末影人'/133, l='MpServer', x=-258.96, y=60.00, z=-1417.90], EntityEnderman['末影人'/134, l='MpServer', x=-260.50, y=60.00, z=-1421.50], EntityEnderman['末影人'/135, l='MpServer', x=-256.50, y=60.00, z=-1418.50], EntityEnderman['末影人'/137, l='MpServer', x=-265.48, y=59.00, z=-1418.60], EntityEnderman['末影人'/139, l='MpServer', x=-261.50, y=60.00, z=-1417.50], EntityEnderman['末影人'/140, l='MpServer', x=-259.89, y=60.00, z=-1417.74], EntityEnderman['末影人'/141, l='MpServer', x=-150.50, y=64.00, z=-1539.50], EntityEnderman['末影人'/142, l='MpServer', x=-149.50, y=64.00, z=-1538.50], EntityEnderman['末影人'/143, l='MpServer', x=-207.50, y=58.00, z=-1489.50], EntityEnderman['末影人'/144, l='MpServer', x=-247.46, y=59.00, z=-1456.45], EntityEnderman['末影人'/146, l='MpServer', x=-204.50, y=58.00, z=-1485.50], EntityEnderman['末影人'/147, l='MpServer', x=-201.50, y=58.00, z=-1485.50], EntityEnderman['末影人'/148, l='MpServer', x=-203.50, y=58.00, z=-1486.50], EntityEnderman['末影人'/149, l='MpServer', x=-192.50, y=59.00, z=-1478.50], EntityEnderman['末影人'/150, l='MpServer', x=-195.50, y=59.00, z=-1475.50], EntityEnderman['末影人'/86, l='MpServer', x=-156.89, y=30.00, z=-1427.51], EntityEnderman['末影人'/151, l='MpServer', x=-231.50, y=61.00, z=-1450.50], EntityGaiaEnderDragonGirl['末影龙女'/152, l='MpServer', x=-233.50, y=61.00, z=-1441.50], EntityGaiaEnderDragonGirl['末影龙女'/153, l='MpServer', x=-219.50, y=62.00, z=-1463.50], EntityEnderman['末影人'/94, l='MpServer', x=-282.50, y=47.00, z=-1550.50], EntityEnderman['末影人'/95, l='MpServer', x=-279.50, y=47.00, z=-1545.50], EntityEnderman['末影人'/160, l='MpServer', x=-203.50, y=63.00, z=-1542.50], EntityEnderman['末影人'/161, l='MpServer', x=-243.50, y=52.00, z=-1503.50], EntityEnderman['末影人'/162, l='MpServer', x=-293.50, y=57.00, z=-1448.50], EntityEnderman['末影人'/102, l='MpServer', x=-167.40, y=57.00, z=-1493.60], EntityEnderman['末影人'/103, l='MpServer', x=-174.50, y=58.00, z=-1499.50], EntityEnderman['末影人'/104, l='MpServer', x=-172.50, y=58.00, z=-1497.50], EntityEnderman['末影人'/105, l='MpServer', x=-174.50, y=58.00, z=-1493.50], EntityPlayerSP['Z'/83, l='MpServer', x=-215.03, y=83.59, z=-1494.85], EntityGaiaEnderDragonGirl['末影龙女'/106, l='MpServer', x=-205.50, y=59.92, z=-1478.46], EntityEnderman['末影人'/107, l='MpServer', x=-193.83, y=59.00, z=-1479.68], EntityEnderman['末影人'/108, l='MpServer', x=-189.24, y=58.00, z=-1480.33], EntityEnderman['末影人'/113, l='MpServer', x=-182.50, y=59.00, z=-1461.50], EntityEnderman['末影人'/114, l='MpServer', x=-184.50, y=59.00, z=-1465.50], EntityGaiaEnderDragonGirl['末影龙女'/115, l='MpServer', x=-181.50, y=59.00, z=-1458.50], EntityEnderman['末影人'/116, l='MpServer', x=-161.47, y=31.00, z=-1425.90], EntityEnderman['末影人'/124, l='MpServer', x=-223.50, y=59.00, z=-1512.50], EntityEnderman['末影人'/125, l='MpServer', x=-218.50, y=59.00, z=-1507.50], EntityEnderman['末影人'/126, l='MpServer', x=-215.56, y=59.00, z=-1510.53], EntityEnderman['末影人'/127, l='MpServer', x=-218.50, y=59.00, z=-1506.50]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_201, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3002490728 bytes (2863 MB) / 4211081216 bytes (4016 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 16, tcache: 1, allocated: 3, tallocated: 104
  FML: MCP 9.42 Powered by Forge 14.23.5.2836 Optifine OptiFine_1.12.2_HD_U_E3 87 mods loaded, 87 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version                  | Source                                                  | Signature                                |
       |:------ |:-------------------- |:------------------------ |:------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                           | None                                     |
       | LCHIJA | mcp                  | 9.42                     | minecraft.jar                                           | None                                     |
       | LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2836.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                | 14.23.5.2836             | forge-1.12.2-14.23.5.2836.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | jecharacters         | 1.12.0-3.3.0             | JustEnoughCharacters-1.12.0-3.3.0.jar                   | None                                     |
       | LCHIJA | foamfixcore          | 7.7.4                    | minecraft.jar                                           | None                                     |
       | LCHIJA | deconstruction       | 3.0.4                    | [MC1.12.2]DeconTable-3.0.4.jar                          | None                                     |
       | LCHIJA | ambientsounds        | 3.0                      | AmbientSounds_v3.0.4_mc1.12.2.jar                       | None                                     |
       | LCHIJA | antiqueatlas         | 4.5.0                    | antiqueatlas-1.12.2-4.5.0.jar                           | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | antiqueatlasoverlay  | 1.2                      | antiqueatlas-1.12.2-4.5.0.jar                           | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | autoplant            | 1.12-1.0.0               | autoplant-1.12-1.0.0.jar                                | None                                     |
       | LCHIJA | jei                  | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                               | None                                     |
       | LCHIJA | quark                | r1.5-146                 | Quark-r1.5-146.jar                                      | None                                     |
       | LCHIJA | autoreglib           | 1.3-26                   | AutoRegLib-1.3-26.jar                                   | None                                     |
       | LCHIJA | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                                  | None                                     |
       | LCHIJA | betteranimals        | 3.1                      | betteranimals-4.0.jar                                   | None                                     |
       | LCHIJA | betteranimalsplus    | 5.0.2                    | betteranimalsplus-5.0.2 [汉化].jar                        | None                                     |
       | LCHIJA | betterbuilderswands  | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513 [汉化].jar  | None                                     |
       | LCHIJA | forgelin             | 1.8.2                    | Forgelin-1.8.2.jar                                      | None                                     |
       | LCHIJA | betterfoliage        | 2.2.0                    | BetterFoliage-MC1.12-2.2.0.jar                          | None                                     |
       | LCHIJA | biomesoplenty        | 7.0.1.2427               | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar           | None                                     |
       | LCHIJA | blockdrops           | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                             | None                                     |
       | LCHIJA | buildinggadgets      | 2.6.8                    | BuildingGadgets-2.6.8.jar                               | None                                     |
       | LCHIJA | bullseye             | 3.0.7                    | Bullseye-1.12.2-3.0.7.jar                               | None                                     |
       | LCHIJA | ctm                  | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                               | None                                     |
       | LCHIJA | chisel               | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35 [汉化].jar                       | None                                     |
       | LCHIJA | mantle               | 1.12-1.3.3.49            | Mantle-1.12-1.3.3.49.jar                                | None                                     |
       | LCHIJA | tconstruct           | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                        | None                                     |
       | LCHIJA | ceramics             | 1.12-1.3.7               | Ceramics-1.12-1.3.7 [汉化].jar                            | None                                     |
       | LCHIJA | comforts             | 1.4.1.1                  | comforts-1.12.2-1.4.1.1.jar                             | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | reskillable          | 1.12.2-GRADLE:BUILD      | Reskillable-1.12.2-1.12.5 [汉化].jar                      | None                                     |
       | LCHIJA | thaumcraft           | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                        | None                                     |
       | LCHIJA | railcraft            | 12.0.0                   | railcraft-12.0.0.jar                                    | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | immersiveengineering | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                        | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | compatskills         | 1.12.2-1.15.0            | CompatSkills-1.12.2-1.15.0.jar                          | None                                     |
       | LCHIJA | cookingforblockheads | 6.4.70                   | CookingForBlockheads_1.12.2-6.4.70.jar                  | None                                     |
       | LCHIJA | dynamictrees         | 1.12.2-0.9.4             | DynamicTrees-1.12.2-0.9.4 [汉化].jar                      | None                                     |
       | LCHIJA | dynamictreesbop      | 1.12.2-1.4.1e            | DynamicTreesBOP-1.12.2-1.4.1e [汉化].jar                  | None                                     |
       | LCHIJA | rustic               | 1.1.0                    | rustic-1.1.0 [汉化].jar                                   | None                                     |
       | LCHIJA | dynamictreestc       | 1.12.2-1.4.1e            | DynamicTreesTC-1.12.2-1.4.1e.jar                        | None                                     |
       | LCHIJA | silentlib            | 3.0.13                   | SilentLib-1.12.2-3.0.13-167.jar                         | None                                     |
       | LCHIJA | extendeddays         | 0.2.9                    | ExtendedDays-1.12.2-0.2.9-28.jar                        | None                                     |
       | LCHIJA | familiarfauna        | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar                         | None                                     |
       | LCHIJA | farmingforblockheads | 3.1.26                   | FarmingForBlockheads_1.12.2-3.1.26.jar                  | None                                     |
       | LCHIJA | fastleafdecay        | v14                      | FastLeafDecay-v14.jar                                   | None                                     |
       | LCHIJA | foamfix              | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                               | None                                     |
       | LCHIJA | cfm                  | 6.2.0                    | furniture-6.2.0-1.12.2 [汉化].jar                         | None                                     |
       | LCHIJA | grimoireofgaia       | 1.6.9.3                  | GrimoireOfGaia3-1.12.2-1.6.9.3.jar                      | None                                     |
       | LCHIJA | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                             | None                                     |
       | LCHIJA | immersivepetroleum   | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9 [汉化].jar                | None                                     |
       | LCHIJA | immersivetech        | 1.3.10                   | immersivetech-1.12-1.3.10 [汉化].jar                      | None                                     |
       | LCHIJA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                                | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironchest            | 1.12.2-7.0.59.842        | ironchest-1.12.2-7.0.59.842.jar                         | None                                     |
       | LCHIJA | jeiintegration       | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar                      | None                                     |
       | LCHIJA | jeresources          | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar                 | None                                     |
       | LCHIJA | lostcities           | 2.0.17                   | lostcities-1.12-2.0.17.jar                              | None                                     |
       | LCHIJA | malisiscore          | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                            | None                                     |
       | LCHIJA | malisisdoors         | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                           | None                                     |
       | LCHIJA | mousetweaks          | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                           | None                                     |
       | LCHIJA | neat                 | 1.4-17                   | Neat 1.4-17.jar                                         | None                                     |
       | LCHIJA | recipehandler        | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar                   | None                                     |
       | LCHIJA | omlib                | 3.0.1-162                | omlib-1.12.2-3.0.1-162.jar                              | None                                     |
       | LCHIJA | openmodularturrets   | 3.0.1-264                | openmodularturrets-1.12.2-3.0.1-264.jar                 | None                                     |
       | LCHIJA | parry                | 1.0                      | parry-1.0-hotfix [汉化].jar                               | None                                     |
       | LCHIJA | shetiphiancore       | 3.5.9                    | shetiphiancore-1.12.0-3.5.9.jar                         | None                                     |
       | LCHIJA | platforms            | 1.4.6                    | platforms-1.12.0-1.4.6 [汉化].jar                         | None                                     |
       | LCHIJA | xreliquary           | 1.12.2-1.3.4.786         | Reliquary-1.12.2-1.3.4.786.jar                          | None                                     |
       | LCHIJA | roughmobs            | 2.0.0                    | roughmobs2-1.12.2_2.0.14.jar                            | None                                     |
       | LCHIJA | sereneseasons        | 1.2.15                   | SereneSeasons-1.12.2-1.2.15-universal.jar               | None                                     |
       | LCHIJA | soundphysics         | 1.0.4                    | Sound-Physics-1.12.2.jar                                | None                                     |
       | LCHIJA | spartanshields       | 1.4.1                    | SpartanShields-1.12.2-1.4.1 [汉化].jar                    | None                                     |
       | LCHIJA | tc6aspects4jei       | 0.0.2a                   | tc6aspects4jei-0.0.2a.jar                               | None                                     |
       | LCHIJA | thaumicjei           | 1.5.8                    | ThaumicJEI-1.12.2-1.5.8-26.jar                          | None                                     |
       | LCHIJA | thaumicperiphery     | 0.3.0                    | thaumicperiphery-0.3.0 [汉化].jar                         | None                                     |
       | LCHIJA | toolbelt             | 1.7.1                    | ToolBelt-1.12.0-1.7.1.jar                               | None                                     |
       | LCHIJA | treechopper          | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                            | None                                     |
       | LCHIJA | vanillafix           | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                                | None                                     |
       | LCHIJA | wailaharvestability  | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar                   | None                                     |
       | LCHIJA | wanionlib            | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                                | None                                     |
       | LCHIJA | wawla                | 2.5.269                  | Wawla-1.12.2-2.5.269.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | wearablebackpacks    | 3.1.3                    | WearableBackpacks-1.12.2-3.1.3.jar                      | None                                     |
       | LCHIJA | xaerominimap         | 1.16.6                   | Xaeros_Minimap_1.16.6_Forge_1.12.jar                    | None                                     |
       | LCHIJA | xaeroworldmap        | 1.3.4.1                  | XaerosWorldMap_1.3.4.1_Forge_1.12.jar                   | None                                     |
       | LCHIJA | structurize          | 1.12.2-0.10.79-ALPHA     | structurize-1.12.2-0.10.79-ALPHA.jar                    | None                                     |
       | LCHIJA | minecolonies         | 1.12.2-0.10.259-RELEASE  | minecolonies-1.12.2-0.10.259-RELEASE-universal [汉化].jar | None                                     |
       | LCHIJA | snowrealmagic        | 0.3.1                    | SnowRealMagic-0.3.1.jar                                 | None                                     |
       | LCHIJA | unidict              | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                                | None                                     |
  Loaded coremods (and transformers): LoadingPlugin (Quark-r1.5-146.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      LoadingPlugin (Reskillable-1.12.2-1.12.5 [汉化].jar)
                                        codersafterdark.reskillable.base.asm.ClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      JechCore (JustEnoughCharacters-1.12.0-3.3.0.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
                                        shetiphian.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      Snow! Real Magic! Core Mod (SnowRealMagic-0.3.1-coremod.jar)
                                        snownee.snow.asm.ASMTransformer
                                      CoreModLoader (Sound-Physics-1.12.2.jar)
                                        com.sonicether.soundphysics.CoreModInjector
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.34' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Suspected Mods: Antique Atlas (antiqueatlas), Antique Atlas Overlay (antiqueatlasoverlay)
  Launched Version: HMCL 3.2.112
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.34, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Conquest_1.12.zip
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by tyra314** [comment] 2019-05-02 09:30
Duplicate of #215, which is already fixed on master. We really should push an update...

**Closed as completed by tyra314** 2019-05-02 09:30 UTC
Labels: type: bug, type: duplicate, version: 1.12
