### ISSUE TITLE
Other players cannot join the "opened to LAN" session

### ISSUE THREAD

**Issue by felixdivo** [Hunternif/AntiqueAtlas#328] opened 2021-03-01 13:26 UTC
**Describe the bug**
Other players cannot join the "opened to LAN" session. They can log in, it take a short wihle, but before they leave their loading screen they are kicked.

**To Reproduce**
Steps to reproduce the behavior (this worked reliably for us):
1. Create a world
2. Click on 'open to LAN'
3. Let someone else join

**Expected behavior**
It just works as in single player, for each one individually.

**Screenshots**
None.

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.4
 - Forge: 35.1.37
 - AntiqueAtlas: 5.4.4-forge

**Additional context**

Crash log with exception (User *Halladihopp* tries to join):
```
[23:16:19] [Server thread/INFO]: Halladihopp[/SOME_IP:SOME_PORT] logged in with entity id 53621 at (79.5, 68.0, 5.5)
[23:16:19] [Server thread/INFO]: Halladihopp joined the game
[23:16:19] [Server thread/ERROR]: Exception caught during firing event: null
	Index: 10
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2910/1394284408@2bdb7ab5
		2: ASM: class com._idrae.travelers_index.events.EventBusSubscriber onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		3: ASM: class vazkii.patchouli.common.handler.PlayerJoinHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		4: ASM: class net.blay09.mods.waystones.handler.LoginHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		5: ASM: sereneseasons.handler.season.SeasonHandler@26a43989 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		6: ASM: class com.possible_triangle.brazier.config.LoginHandler playerJoined(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		7: ASM: class xreliquary.handler.CommonEventHandler blameDrullkus(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		8: ASM: net.minecraftforge.common.ForgeInternalHandler@5cba335f playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		9: ASM: class net.mehvahdjukaar.supplementaries.world.data.GlobeData onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		10: ASM: class hunternif.mc.impl.atlas.forge.ForgeEvent playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		11: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		12: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		13: ASM: class hellfirepvp.astralsorcery.common.event.handler.EventHandlerCache onPlayerConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		14: ASM: class blusunrize.immersiveengineering.common.blocks.multiblocks.StaticTemplateManager onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		15: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@1594172e playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		16: ASM: mcjty.theoneprobe.ForgeEventHandlers@7dfe694 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		17: ASM: team.creative.creativecore.common.config.event.ConfigEventHandler@e64281e playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		18: ASM: dev.gigaherz.toolbelt.slot.BeltExtensionSlot$EventHandlers@652230b7 joinWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		19: net.minecraftforge.eventbus.EventBus$$Lambda$2910/1394284408@34ebac8
		20: ASM: vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule@47581226 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.NullPointerException
	at hunternif.mc.impl.atlas.marker.GlobalMarkersDataHandler.onPlayerLogin(GlobalMarkersDataHandler.java:59)
	at hunternif.mc.impl.atlas.forge.ForgeEvent.playerJoin(ForgeEvent.java:51)
	at net.minecraftforge.eventbus.ASMEventHandler_685_ForgeEvent_playerJoin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[23:16:19] [Server thread/WARN]: Failed to handle packet for /SOME_IP:SOME_PORT
java.lang.NullPointerException: null
	at hunternif.mc.impl.atlas.marker.GlobalMarkersDataHandler.onPlayerLogin(GlobalMarkersDataHandler.java:59) ~[antiqueatlas:?]
	at hunternif.mc.impl.atlas.forge.ForgeEvent.playerJoin(ForgeEvent.java:51) ~[antiqueatlas:?]
	at net.minecraftforge.eventbus.ASMEventHandler_685_ForgeEvent_playerJoin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[23:16:19] [Render thread/INFO]: [CHAT] Halladihopp joined the game
[23:16:20] [Netty Server IO #5/INFO]: Skipping config sync, No mods have registered a syncable config.
[23:16:23] [Server thread/INFO]: Halladihopp lost connection: Disconnected
[23:16:23] [Server thread/INFO]: Halladihopp left the game
[23:16:23] [Render thread/INFO]: [CHAT] Halladihopp left the game
```

The exception points [here](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/blob/1.16-fabric/src/main/java/hunternif/mc/impl/atlas/marker/GlobalMarkersDataHandler.java#L59).

**Comment by Alexander3847575** [comment] 2021-03-07 10:37
Can confirm, this happens to me too.

**Comment by tyra314** [comment] 2021-03-11 00:44
Duplicate of #314

**Closed as completed by tyra314** 2021-03-11 00:44 UTC
Labels: type: bug, type: duplicate, version: 1.16, mod loader: forge
