### ISSUE TITLE
Optifine/Antique Atlas layering issue

### ISSUE THREAD

**Issue by bozosbinted** [Hunternif/AntiqueAtlas#427] opened 2022-05-21 11:44 UTC
Seems similar to #301, but is occurring in version 1.16.5 on Antique atlas 5.4.4-forge. Exact same symptoms.
Map appears translucent over bodies of water or ice when shaders are enabled. I should mention that this can be reproduced using only optifine's internal shaders.

 - Minecraft: 1.16.5
 - Forge: 36.2.20
 - AntiqueAtlas: 5.4.4-forge

![2022-05-21_07 37 19](https://user-images.githubusercontent.com/105974158/169650087-d630efa8-7a66-4d92-9106-2ee04740110a.png)
no shaders

![2022-05-21_07 39 33](https://user-images.githubusercontent.com/105974158/169650099-bb49c418-d1ed-4b82-b70d-5f63361090ad.png)
shaders

sorry if this has already been fixed; i wasn't smart enough to find a solution on the other bug pages :)

**Comment by tyra314** [comment] 2022-05-21 13:35
Duplicate of #301 

Already fixed in 6.0.1

**Closed as completed by tyra314** 2022-05-21 13:35 UTC
Labels: type: bug, type: duplicate, version: 1.16, mod loader: forge
