### ISSUE TITLE
Cant craft anything 1.16.4 forge

### ISSUE THREAD

**Issue by captinwill** [Hunternif/AntiqueAtlas#300] opened 2021-01-15 19:38 UTC
i have been playing this world and i decide to get this mod and then when i go to craft the atlas of anything my game crashes here is log 
[crash-2021-01-15_14.30.30-client.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/5822595/crash-2021-01-15_14.30.30-client.txt)

**Comment by captinwill** [comment] 2021-01-15 19:39
and i used vanilla crafting table

**Comment by tyra314** [comment] 2021-01-15 21:01
Duplicate of #297

**Closed as completed by tyra314** 2021-01-15 21:01 UTC
Labels: type: bug, type: duplicate, version: 1.16, mod loader: forge
