### ISSUE TITLE
Crash upon Open

### ISSUE THREAD

**Issue by AlexClose** [Hunternif/AntiqueAtlas#351] opened 2021-05-17 13:54 UTC
**Describe the bug**

**To Reproduce**
1. open minecraft
2. press play
3. crash

**Fabric version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Fabric Launcher: [e.g. 0.11.1]
 - Fabric API: [e.g. 0.29.4]
 - AntiqueAtlas: [e.g. 5.4.4-fabric]

**Expected behavior**
When I open the launcher its fine but I click play and it closes and crashes, opens the following error.
-
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'antiqueatlas'!
Exit Code: -1

**Comment by tyra314** [comment] 2021-05-19 08:25
Duplicate of #314

**Closed as completed by tyra314** 2021-05-19 08:25 UTC
Labels: type: duplicate
