### ISSUE TITLE
Minecraft gives a mod error with Unionlib and some others

### ISSUE THREAD

**Issue by Elias2804** [Hunternif/AntiqueAtlas#451] opened 2022-11-12 13:37 UTC
**Describe the bug**
When launching with Antique Atlas, its dependencies and with Unionlib, it gives the following error when it launches:
"Antique Atlast (antiqueatlas) has failed to load correctly
java.lang.reflect.InvocationTargetException: null" 

**To Reproduce**
1. Install minecraft 1.18.2, Antique atlas and its dependencies, and unionlib.
2. run this modded minecraft
3. Observe the problem 

**Expected behavior**
It is expected that minecraft launches without this problem

**Screenshots**
[Screenshot of the error](https://imgur.com/a/BQE1UbL)

**Version information:**
 - AntiqueAtlas: 7.0.3-forge-mc1.18,.2
 - Minecraft: 1.18.2
 - Forge: 40.1.70
 - Fabric API: 6.4.90
 
**Additional context**
[Error log with unionlib](https://pastebin.com/rj08wL2u)

-----
Though, this doesn't seem like it's limited to Unionlib, but for the life of me I cannot figure out what else is causing the error.
If anyone cares, here's some logs on me trying to launch my modpack with Antique Atlas:
[Latest.log](https://pastebin.com/SUSRez3N)
[crash-fml.txt](https://pastebin.com/UeS8vXft)

**Comment by tyra314** [comment] 2022-11-12 14:17
It is UnionLib.

Duplicate of #447

**Closed as completed by tyra314** 2022-11-12 14:17 UTC
Labels: type: duplicate, mod loader: fabric, mod loader: forge, version: 1.18, type: crash
