### ISSUE TITLE
Crash on world create

### ISSUE THREAD

**Issue by AdnanuReeves** [Hunternif/AntiqueAtlas#309] opened 2021-01-26 20:39 UTC
Using the latest forge version for 1.16.5 and latest forge antique atlas version crashing when creating world

https://paste.ubuntu.com/p/DGngbZH8yB/

Works fine as soon as I remove the mod.

**Comment by tyra314** [comment] 2021-04-25 15:20
While this one was first, I marked way too many other issues as duplicates of #314 as well. So:

Duplicate of #314

**Closed as completed by tyra314** 2021-04-25 15:20 UTC
Labels: type: bug, version: 1.16, mod loader: forge
