### ISSUE TITLE
unable to join worlds using Antique Atlas (LAN)

### ISSUE THREAD

**Issue by DarkQueenYuuki** [Hunternif/AntiqueAtlas#368] opened 2021-07-13 23:39 UTC
**Describe the bug**
The host is able to create and enter the world just fine, able to play and open the world to LAN. Any players trying to join the same world get to the "joining world" prompt before being kicked from the world and given the "internal server error" screen.

I understand there have been several reports for similar issues, but what I can find are closed reports from months back so I am not sure that this isn't a new instance.

**To Reproduce**
1. loading up any modpack with AntiqueAtlas installed, on two or more accounts
2. host opening a new single player world and opening to LAN
3. other accounts joining the (now) multiplayer world
4. see error

**Expected behavior**
For multiple players to be able to play on the same world, with AA installed.

**Forge version information (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.32
 - AntiqueAtlas: 5.4.4-forge

**Additional context**
I have retested the issue just today, below is the log from the latest attempt from the account unable to join (could not get the text file to attach):

[17:46:46] [main/INFO]: ModLauncher running: args [--username, CptnSkullKid, --version, forge-36.1.32, --gameDir, C:\Users\skull\curseforge\minecraft\Instances\Yuuki's TestPack, --assetsDir, C:\Users\skull\curseforge\minecraft\Install\assets, --assetIndex, 1.16, --uuid, 29d5cecd4f8a4748bf4d633e6b1fc2aa, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1920, --height, 1080, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.32, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[17:46:46] [main/INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation
[17:46:46] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[17:46:47] [main/INFO]: OptiFineTransformationService.onLoad
[17:46:47] [main/INFO]: OptiFine ZIP file: C:\Users\skull\curseforge\minecraft\Instances\Yuuki's TestPack\mods\OptiFine_1.16.5_HD_U_G8.jar
[17:46:47] [main/INFO]: Target.PRE_CLASS is available
[17:46:47] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[17:46:47] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/skull/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[17:46:47] [main/INFO]: OptiFineTransformationService.initialize
[17:46:48] [main/INFO]: OptiFineTransformationService.transformers
[17:46:48] [main/INFO]: Targets: 311
[17:46:48] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[17:46:48] [main/ERROR]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
[17:46:48] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-36.1.32, --gameDir, C:\Users\skull\curseforge\minecraft\Instances\Yuuki's TestPack, --assetsDir, C:\Users\skull\curseforge\minecraft\Install\assets, --uuid, 29d5cecd4f8a4748bf4d633e6b1fc2aa, --username, CptnSkullKid, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1920, --height, 1080]
[17:46:53] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:46:54] [Render thread/INFO]: Setting user: CptnSkullKid
[17:46:54] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraft.launchwrapper.Launch
[17:46:54] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[17:46:54] [Render thread/INFO]: [OptiFine] 
[17:46:54] [Render thread/INFO]: [OptiFine] OptiFine_1.16.5_HD_U_G8
[17:46:54] [Render thread/INFO]: [OptiFine] Build: 20210515-161946
[17:46:54] [Render thread/INFO]: [OptiFine] OS: Windows 10 (amd64) version 10.0
[17:46:54] [Render thread/INFO]: [OptiFine] Java: 1.8.0_51, Oracle Corporation
[17:46:54] [Render thread/INFO]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[17:46:54] [Render thread/INFO]: [OptiFine] LWJGL: 3.3.0 Win32 WGL EGL OSMesa VisualC DLL
[17:46:54] [Render thread/INFO]: [OptiFine] OpenGL: AMD Radeon(TM) Graphics, version 4.6.13596 Compatibility Profile Context 20.10.20.10 27.20.11020.10001, ATI Technologies Inc.
[17:46:54] [Render thread/INFO]: [OptiFine] OpenGL Version: 4.6.13596
[17:46:54] [Render thread/INFO]: [OptiFine] OpenGL Fancy fog: Not available (GL_NV_fog_distance)
[17:46:54] [Render thread/INFO]: [OptiFine] Maximum texture size: 16384x16384
[17:46:54] [VersionCheck/INFO]: [OptiFine] Checking for new version
[17:46:54] [Render thread/INFO]: [Shaders] OpenGL Version: 4.6.13596 Compatibility Profile Context 20.10.20.10 27.20.11020.10001
[17:46:54] [Render thread/INFO]: [Shaders] Vendor:  ATI Technologies Inc.
[17:46:54] [Render thread/INFO]: [Shaders] Renderer: AMD Radeon(TM) Graphics
[17:46:54] [Render thread/INFO]: [Shaders] Capabilities:  2.0  2.1  3.0  3.2  4.0 
[17:46:54] [Render thread/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[17:46:54] [Render thread/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[17:46:54] [Render thread/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 32
[17:46:54] [Render thread/INFO]: [Shaders] Load shaders configuration.
[17:46:54] [Render thread/INFO]: [Shaders] Save shaders configuration.
[17:46:54] [Render thread/INFO]: [Shaders] No shaderpack loaded.
[17:46:54] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.Loader
[17:46:54] [modloading-worker-2/INFO]: Forge mod loading, version 36.1.32, for MC 1.16.5 with MCP 20210115.111550
[17:46:54] [modloading-worker-2/INFO]: MinecraftForge v36.1.32 Initialized
[17:46:55] [VersionCheck/INFO]: [OptiFine] Version found: G7
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:ocean
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:plains
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:desert
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:swamp
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:river
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:frozen_ocean
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:frozen_river
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:snowy_tundra
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:beach
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:desert_hills
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:wooded_hills
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:mountain_edge
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:deep_ocean
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:dark_forest
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:wooded_mountains
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:small_end_islands
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:end_midlands
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:end_highlands
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:end_barrens
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:warm_ocean
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:lukewarm_ocean
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:cold_ocean
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:deep_warm_ocean
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:deep_lukewarm_ocean
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:deep_cold_ocean
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:the_void
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:desert_lakes
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:gravelly_mountains
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:taiga_mountains
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:swamp_hills
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:modified_jungle
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:dark_forest_hills
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:modified_gravelly_mountains
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:modified_wooded_badlands_plateau
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:modified_badlands_plateau
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:bamboo_jungle
[17:46:56] [Render thread/INFO]: Auto-registered standard texture set for biome minecraft:bamboo_jungle_hills
[17:46:56] [Render thread/INFO]: Narrator library for x64 successfully loaded
[17:46:56] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[17:46:56] [Render thread/INFO]: [OptiFine] *** Reloading textures ***
[17:46:56] [Render thread/INFO]: [OptiFine] Resource packs: Mod Resources
[17:46:56] [Render thread/INFO]: [OptiFine] *** Reflector Forge ***
[17:46:56] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[17:46:56] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[17:46:56] [Worker-Main-14/INFO]: [OptiFine] Multitexture: false
[17:46:56] [Worker-Main-13/INFO]: [OptiFine] Multitexture: false
[17:46:56] [Worker-Main-9/INFO]: [OptiFine] Multitexture: false
[17:46:56] [Render thread/INFO]: [OptiFine] (Reflector) Field not present: net.minecraftforge.client.model.pipeline.LightUtil.itemConsumer
[17:46:56] [Render thread/INFO]: [OptiFine] (Reflector) Field not present: net.minecraftforge.client.model.pipeline.LightUtil.tessellator
[17:46:56] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.ModContainer
[17:46:56] [Render thread/INFO]: [OptiFine] *** Reflector Vanilla ***
[17:46:58] [Forge Version Check/INFO]: [forge] Found status: AHEAD Current: 36.1.32 Target: null
[17:46:59] [Worker-Main-10/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[17:46:59] [Worker-Main-10/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[17:46:59] [Worker-Main-10/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[17:46:59] [Worker-Main-10/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] Multitexture: false
[17:46:59] [Worker-Main-10/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] Multipass connected textures: false
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/00_glass_white/glass_pane_white.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/00_glass_white/glass_white.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/01_glass_orange/glass_orange.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/01_glass_orange/glass_pane_orange.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/02_glass_magenta/glass_magenta.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/02_glass_magenta/glass_pane_magenta.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/03_glass_light_blue/glass_light_blue.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/03_glass_light_blue/glass_pane_light_blue.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/04_glass_yellow/glass_pane_yellow.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/04_glass_yellow/glass_yellow.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/05_glass_lime/glass_lime.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/05_glass_lime/glass_pane_lime.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/06_glass_pink/glass_pane_pink.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/06_glass_pink/glass_pink.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/07_glass_gray/glass_gray.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/07_glass_gray/glass_pane_gray.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/08_glass_light_gray/glass_light_gray.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/08_glass_light_gray/glass_pane_light_gray.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/09_glass_cyan/glass_cyan.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/09_glass_cyan/glass_pane_cyan.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/10_glass_purple/glass_pane_purple.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/10_glass_purple/glass_purple.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/11_glass_blue/glass_blue.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/11_glass_blue/glass_pane_blue.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/12_glass_brown/glass_brown.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/12_glass_brown/glass_pane_brown.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/13_glass_green/glass_green.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/13_glass_green/glass_pane_green.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/14_glass_red/glass_pane_red.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/14_glass_red/glass_red.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/15_glass_black/glass_black.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/15_glass_black/glass_pane_black.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/20_glass/glass.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/20_glass/glass_pane.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/30_bookshelf/bookshelf.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/40_sandstone/sandstone.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] ConnectedTextures: optifine/ctm/default/41_red_sandstone/red_sandstone.properties
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] Multipass connected textures: false
[17:46:59] [Worker-Main-10/INFO]: [OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties
[17:47:02] [Worker-Main-10/INFO]: [OptiFine] Mipmap levels: 4
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Multitexture: false
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Sprite size: 64
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Mipmap levels: 6
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Multitexture: false
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Sprite size: 64
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Mipmap levels: 6
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Multitexture: false
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Sprite size: 64
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Mipmap levels: 6
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Multitexture: false
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Sprite size: 64
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Mipmap levels: 6
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Multitexture: false
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Sprite size: 64
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Mipmap levels: 6
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Multitexture: false
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Sprite size: 64
[17:47:03] [Worker-Main-10/INFO]: [OptiFine] Mipmap levels: 6
[17:47:04] [Render thread/INFO]: OpenAL initialized.
[17:47:04] [Render thread/INFO]: Sound engine started
[17:47:05] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[17:47:05] [Render thread/INFO]: [OptiFine] Animated sprites: 43
[17:47:05] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/signs.png-atlas
[17:47:05] [Render thread/INFO]: [OptiFine] Animated sprites: 0
[17:47:05] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17:47:05] [Render thread/INFO]: [OptiFine] Animated sprites: 0
[17:47:05] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17:47:05] [Render thread/INFO]: [OptiFine] Animated sprites: 0
[17:47:05] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17:47:05] [Render thread/INFO]: [OptiFine] Animated sprites: 0
[17:47:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17:47:05] [Render thread/INFO]: [OptiFine] Animated sprites: 0
[17:47:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:47:05] [Render thread/INFO]: [OptiFine] Animated sprites: 0
[17:47:05] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[17:47:05] [Render thread/INFO]: [OptiFine] Animated sprites: 0
[17:47:05] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:47:05] [Render thread/INFO]: [OptiFine] Animated sprites: 0
[17:47:05] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:47:05] [Render thread/INFO]: [OptiFine] Animated sprites: 0
[17:47:05] [Render thread/INFO]: [OptiFine] *** Reloading custom textures ***
[17:47:05] [Render thread/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[17:47:05] [Render thread/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[17:47:05] [Render thread/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[17:47:08] [Render thread/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[17:47:08] [Render thread/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[17:47:08] [Render thread/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[17:47:08] [Render thread/INFO]: [OptiFine] Disable Forge light pipeline
[17:47:08] [Render thread/INFO]: [OptiFine] Set ForgeConfig.CLIENT.forgeLightPipelineEnabled=false
[17:47:42] [Render thread/INFO]: Connecting to 192.168.0.231, 51007
[17:47:49] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[17:47:49] [Netty Client IO #0/INFO]: Connected to a modded server.
[17:47:50] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:47:50] [Render thread/FATAL]: Error executing task on Client
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraftforge.network.NetworkFilters.lambda$injectIfNecessary$1(NetworkFilters.java:48) ~[?:?]
	at net.minecraftforge.network.NetworkFilters$$Lambda$4789/1978560393.accept(Unknown Source) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:146) ~[guava-21.0.jar:?]
	at net.minecraftforge.network.NetworkFilters.injectIfNecessary(NetworkFilters.java:44) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.sendMCRegistryPackets(NetworkHooks.java:121) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147282_a(ClientPlayNetHandler.java:399) ~[?:?]
	at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:110) ~[?:?]
	at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:18) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$4667/1714936261.run(Unknown Source) ~[?:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.32.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$448/2084486251.call(Unknown Source) [forge-1.16.5-36.1.32.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[17:47:54] [Render thread/INFO]: Connecting to 192.168.0.231, 51007
[17:47:56] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[17:47:56] [Netty Client IO #1/INFO]: Connected to a modded server.
[17:47:57] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'

Minecraft itself did not crash at any point and so do not have a crash log to post. This instance only had AA and Waystones installed (no Antique Waystones) in order to try and pin down the issue.

**Comment by tyra314** [comment] 2021-07-17 17:43
duplicate of #314

**Closed as completed by tyra314** 2021-07-17 17:43 UTC
