### ISSUE TITLE
Multiplayer Kick?

### ISSUE THREAD

**Issue by ChubbsWasTaken** [Hunternif/AntiqueAtlas#350] opened 2021-05-15 17:24 UTC
**Describe the bug**
Whenever Antique Atlas is installed and a LAN world is opened and a players joins, they will start to render in, (Loading Terrain phase) before getting kicked.

**To Reproduce**
1. Start a world and Open to LAN
2. Have a player join
3. Have said player load all the way into the final stage
4. Player gets kicked

**Expected behavior**
idk man, for it to not crash

**Forge version information (please complete the following information):**
 - Minecraft: [1.16.5]
 - Forge: [36.1.13]
 - AntiqueAtlas: [5.4.4-forge]

**Additional context**
Seems somewhat strange, could be newer forge versions causing it. in which case an update of you guys' mod would be needed, please look into this
Thanks,

**Comment by tyra314** [comment] 2021-05-19 08:26
Duplicate of #314

**Closed as completed by tyra314** 2021-05-19 08:26 UTC
