### ISSUE TITLE
[Feature Request] Waypoint Page

### ISSUE THREAD

**Issue by Darkosto** [Hunternif/AntiqueAtlas#156] opened 2017-12-15 01:39 UTC
Hello!

I have an interesting idea to share: Is it possible to have a page in the atlas dedicated to all the waypoints the player has created? When clicked maybe it can flip back to the map and focus on the point? I've found that I have so many waypoints and much of my time is trying to find the one I'm looking for. 

Or maybe just a filter to certain icons?

Thanks for the great mod and let me know if I can help out at all!
Darkosto

**Comment by corgiblu** [comment] 2018-08-01 23:19
This would be a great feature! I'm making a pack with a more rustic/low-tech feel and antique atlas is perfect for it. The one feature it's missing (compared to journeymap, and that I'd like) is a waypoint page.

**Comment by Kenkron** [comment] 2018-08-02 18:01
Dang, I need to get on these issues.

**Comment by tyra314** [comment] 2019-01-13 19:45
This is actually a duplicate of #139

**Closed as completed by tyra314** 2019-01-13 19:45 UTC
Labels: type: duplicate, type: enhancement, version: 1.12
