### ISSUE TITLE
Crash when using ESSENTIAL Mod

### ISSUE THREAD

**Issue by Player505** [Hunternif/AntiqueAtlas#442] opened 2022-09-20 07:59 UTC
### When did it crash
loading into a world worked fine however when right clicking on a created atlas to open it the game crashed

### Minecraft version
1.18.2

### Mod loader
Fabric loader 0.14.9

### Loaded mods
- Antique Atlas
- Architectury
- Cloth Config v6
- ESSENTIAL Mod
- Fabric API

### Latest log
https://paste.ee/p/TLdvl

**Comment by tyra314** [comment] 2022-09-20 18:17
While it affects the atlas, this crash seems to be caused by the Essentials mod. You should report it there.

**Comment by Johni0702** [comment] 2022-10-31 07:26
FYI the reason for this issue stems from Essential (and presumably also the mod in #406) adding a mixin accessor for `Screen.children` which by convention is `List<...> getChildren()`.
That accessor is then implicitly overwritten by atlases' completely unrelated `GuiComponent.getChildren`. That method has package-only access and therefore throws an IllegalAccessError when the third-party mod tries to use its accessor.

If you want to, you could change the name of that method to avoid such conflicts in the future. But the only real fix here would be to change Mixin such that e.g. accessors are always name mangled.
Essential will also include a fix for this in its next version. So if you wish to reproduce this in the future, you'll have to start MC with `-Dessential.branch=1.1.0.10` to use the old version.

**Comment by tyra314** [comment] 2022-10-31 09:37
Thanks for sharing. I'm going to close this then.

For future reference: The solution is to update Essentials mod.

**Closed as completed by tyra314** 2022-10-31 09:37 UTC
Labels: type: mod interaction, status: unconfirmed, mod loader: fabric, mod loader: forge, version: 1.18, type: crash
