### ISSUE TITLE
Water, stained glass and particules render over the Atlas

### ISSUE THREAD

**Issue by Spinbbinder** [Hunternif/AntiqueAtlas#345] opened 2021-04-25 14:19 UTC
Water, stained glass and particules (from potions, torches) are render over the Atlas when hold in hands as in the screeshots below.
It happen in forge 1.16.5 version. Didn't test in over versions.
![image](https://user-images.githubusercontent.com/83171905/115996935-8d31ae00-a5e1-11eb-8ef7-04191348f61b.png)
![image](https://user-images.githubusercontent.com/83171905/115997065-f7e2e980-a5e1-11eb-9954-867fad9e9112.png)

**Comment by tyra314** [comment] 2021-04-25 15:22
Duplicate of #301

**Closed as completed by tyra314** 2021-04-25 15:22 UTC
Labels: type: bug, type: duplicate, version: 1.16, mod loader: forge
