### ISSUE TITLE
Markers invisible in atlas crafted before new version.

### ISSUE THREAD

**Issue by madmax3004** [Hunternif/AntiqueAtlas#246] opened 2019-11-04 21:47 UTC
As the title says:

I have an atlas crafted prior to updating this mod from 4.5.1 to 4.6.0, it had quite a few markers which now do not appear anymore.

I crafted a new atlas and markers do appear in that one (if I place them), but obviously I've only got a tiny area explored in it compared to the main atlas.

Merging the atlases has resulted in an atlas that also does not display markers.

I've traveled quite a bit, so perhaps it's an issue with being too far away from spawn / having too large of an atlas? (Read something about that somewhere)

**Comment by madmax3004** [comment] 2019-11-04 21:53
After further testing, the atlas did get its markers back, but they seem to update somewhat erratically. I had to reclick a couple of times to delete one I duplicated, and I think it only updated after going out of the atlas menu, scrolling on to it to have the HUD display, and then going back into it.

Could this be related to server lag?

**Comment by Qattos** [comment] 2019-11-05 07:46
I have exactly the same issue.

**Comment by Hunternif** [comment] 2019-11-05 09:38
Does this happen in multi-player, or single-player too?
Does this happens to markers you placed manually? What icon did you use for those markers?
Could you please also check the # of the atlas item? E.g. the item label would say "Antique Atlas #0".

**Comment by Qattos** [comment] 2019-11-05 09:51
> Does this happen in multi-player, or single-player too?
> Does this happens to markers you placed manually? What icon did you use for those markers?
> Could you please also check the # of the atlas item? E.g. the item label would say "Antique Atlas #0".

- In SP for me.
- It happens to markers I place on an Atlas I had from an older version of your mod.
- It removed all the markers I had before updating the mod.
- Not sure if it's not working for all the markers because I only tried 3 or 4 markers after updating, but I really think it's not working for all of them because I had most of the markers on my Atlas before updating and they all disappeared after updating.
- I'll check the # of the Atlas item when I play next time.

**Comment by Hunternif** [comment] 2019-11-05 09:56
@Qattos can you send me your atlas data files? Navigate to your `.minecraft` directory, find your world under `saves` and there should be a folder called something like `antiqueAtlas`. Can you zip all of it and post it here please?
I think that the old markers are still there, just maybe not displayed correctly. And describe what some of them looked like, if you can remember.

**Comment by Hunternif** [comment] 2019-11-05 10:05
Also please send the last log.

**Comment by Qattos** [comment] 2019-11-05 10:11
> @Qattos can you send me your atlas data files? Navigate to your `.minecraft` directory, find your world under `saves` and there should be a folder called something like `antiqueAtlas`. Can you zip all of it and post it here please?
> I think that the old markers are still there, just maybe not displayed correctly. And describe what some of them looked like, if you can remember.


[Atlas.zip](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/3808356/Atlas.zip)
[latest.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/3808360/latest.log)
- The markers were mostly the tower marker, X marker (small one and big one), Sword marker, Position marker (that red thing with black dot inside) and the skull marker.
- I'm playing RLCraft.
- There's not AntiqueAtlas folder btw but I found them in data folder.

**Comment by Hunternif** [comment] 2019-11-05 10:52
Thanks!
Did you disable `autoVillageMarkers`, and did you use the house icon for your markers?

**Comment by Qattos** [comment] 2019-11-05 10:59
> Thanks!
> Did you disable `autoVillageMarkers`, and did you use the house icon for your markers?

Nope, I didn't disable anything and no I didn't use the house icon before the update, at least I don't remember using it, I used it after the update but it didn't work, but I think I forgot to mention that the only markers that I can see on my Atlas after the update are the house icons for villages, these are generated whenever I find a village.

**Comment by Hunternif** [comment] 2019-11-05 11:25
Ok, I think I found the issue in my code: #248
I'll try and push the fix tonight.

**Comment by Qattos** [comment] 2019-11-05 11:49
Thank you, I'll check it out tonight.

**Comment by madmax3004** [comment] 2019-11-05 15:41
For me it was in multiplayer on a custom modpack. As mentioned the markers did return after some time *after* I merged it with a new atlas (it wasn't an immediate fix when I did it, they returned after I was messing around / placing / trying to remove markers in the newly crafted atlas).

- It happened in MP.
- I only placed manual markers.
- I used various markers, practically all of them I think?
- The original atlas was #0, the one I crafted to test (which worked) was #1, and after merging I think it got renamed back to #0?

**Comment by Hunternif** [comment] 2019-11-05 15:54
Please try this build, it should bring back all the old markers.
UPDATED: [antiqueatlas-1.12.2-4.6.2.zip](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/3810662/antiqueatlas-1.12.2-4.6.2.zip) (rename it to `.jar`)

**Comment by Qattos** [comment] 2019-11-05 20:59
> Please try this build, it should bring back all the old markers.
> UPDATED: [antiqueatlas-1.12.2-4.6.2.zip](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/3810662/antiqueatlas-1.12.2-4.6.2.zip) (rename it to `.jar`)

I'm happy to report that the issue is fixed, all markers are visible now, I placed a couple then logged out and logged back in and they're still there.
But I noticed that you disabled `autoVillageMarkers`, I guess that's better, at least for me.
Thank you for your work.

**Comment by Hunternif** [comment] 2019-11-05 21:15
`autoVillageMarkers` is controlled by your local settings, so it should not become disabled if you didn't disable it yourself in mod settings. This might be a new issue. What do you see happening that makes you say it's disabled?

I did change the way village markers work. If you turn off the `autoVillageMarkers`, you will not get any new village markers, but the old ones will remain until you log out, or until you delete them. If you turn `autoVillageMarkers` back on, village markers will be added again, when you log in.

**Comment by Qattos** [comment] 2019-11-05 21:57
It wasn't disabled before and I didn't mess with the config file.
Before the update and even before your fix, whenever I find a village it gets marked on my Atlas by a house marker, automatically without me marking it down, now the house markers for villages disappeared, and I just checked my config file and `autoVillageMarkers` is set to true, so not sure what happened there.

**Comment by Hunternif** [comment] 2019-11-05 22:31
They don't reappear when you log back in?
This happens on version 4.6.2?

**Comment by Qattos** [comment] 2019-11-05 23:10
Now it's fixed in 4.6.2

**Closed as completed** 2019-11-06 16:42 UTC
Labels: type: bug, version: 1.12

**Comment by ByakkoX12** [comment] 2019-12-23 15:14
> > Please try this build, it should bring back all the old markers.
> > UPDATED: [antiqueatlas-1.12.2-4.6.2.zip](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/3810662/antiqueatlas-1.12.2-4.6.2.zip) (rename it to `.jar`)
> 
> I'm happy to report that the issue is fixed, all markers are visible now, I placed a couple then logged out and logged back in and they're still there.
> But I noticed that you disabled `autoVillageMarkers`, I guess that's better, at least for me.
> Thank you for your work.

Hello,

How did you fix it. Meaning where did you place the files. what did u do to make it a jar. Whats the process did you do. Please show me. I have the same problem.
