### ISSUE TITLE
java.io.ioexception: an existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by alw4ys-on** [Hunternif/AntiqueAtlas#387] opened 2021-08-15 13:38 UTC
when I open the lan with the mod, no one can log in, right after I removed the mod, everyone was able to log in again

 - Minecraft: 1.16.5
 - Forge: 32.2.2
 - AntiqueAtlas: 5.4.4-forge

**Comment by tyra314** [comment] 2021-08-15 18:11
Duplicate of #314. Update AA

**Closed as completed by tyra314** 2021-08-15 18:11 UTC
Labels: type: duplicate, version: 1.16, mod loader: forge
